// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cartographer/transform/proto/transform.proto

#ifndef PROTOBUF_cartographer_2ftransform_2fproto_2ftransform_2eproto__INCLUDED
#define PROTOBUF_cartographer_2ftransform_2fproto_2ftransform_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3003000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3003000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
namespace cartographer {
namespace transform {
namespace proto {
class Quaterniond;
class QuaterniondDefaultTypeInternal;
extern QuaterniondDefaultTypeInternal _Quaterniond_default_instance_;
class Quaternionf;
class QuaternionfDefaultTypeInternal;
extern QuaternionfDefaultTypeInternal _Quaternionf_default_instance_;
class Rigid2d;
class Rigid2dDefaultTypeInternal;
extern Rigid2dDefaultTypeInternal _Rigid2d_default_instance_;
class Rigid2f;
class Rigid2fDefaultTypeInternal;
extern Rigid2fDefaultTypeInternal _Rigid2f_default_instance_;
class Rigid3d;
class Rigid3dDefaultTypeInternal;
extern Rigid3dDefaultTypeInternal _Rigid3d_default_instance_;
class Rigid3f;
class Rigid3fDefaultTypeInternal;
extern Rigid3fDefaultTypeInternal _Rigid3f_default_instance_;
class Vector2d;
class Vector2dDefaultTypeInternal;
extern Vector2dDefaultTypeInternal _Vector2d_default_instance_;
class Vector2f;
class Vector2fDefaultTypeInternal;
extern Vector2fDefaultTypeInternal _Vector2f_default_instance_;
class Vector3d;
class Vector3dDefaultTypeInternal;
extern Vector3dDefaultTypeInternal _Vector3d_default_instance_;
class Vector3f;
class Vector3fDefaultTypeInternal;
extern Vector3fDefaultTypeInternal _Vector3f_default_instance_;
}  // namespace proto
}  // namespace transform
}  // namespace cartographer

namespace cartographer {
namespace transform {
namespace proto {

namespace protobuf_cartographer_2ftransform_2fproto_2ftransform_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_cartographer_2ftransform_2fproto_2ftransform_2eproto

// ===================================================================

class Vector2d : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:cartographer.transform.proto.Vector2d) */ {
 public:
  Vector2d();
  virtual ~Vector2d();

  Vector2d(const Vector2d& from);

  inline Vector2d& operator=(const Vector2d& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Vector2d& default_instance();

  static inline const Vector2d* internal_default_instance() {
    return reinterpret_cast<const Vector2d*>(
               &_Vector2d_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(Vector2d* other);

  // implements Message ----------------------------------------------

  inline Vector2d* New() const PROTOBUF_FINAL { return New(NULL); }

  Vector2d* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Vector2d& from);
  void MergeFrom(const Vector2d& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Vector2d* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional double x = 1;
  bool has_x() const;
  void clear_x();
  static const int kXFieldNumber = 1;
  double x() const;
  void set_x(double value);

  // optional double y = 2;
  bool has_y() const;
  void clear_y();
  static const int kYFieldNumber = 2;
  double y() const;
  void set_y(double value);

  // @@protoc_insertion_point(class_scope:cartographer.transform.proto.Vector2d)
 private:
  void set_has_x();
  void clear_has_x();
  void set_has_y();
  void clear_has_y();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  double x_;
  double y_;
  friend struct protobuf_cartographer_2ftransform_2fproto_2ftransform_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Vector2f : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:cartographer.transform.proto.Vector2f) */ {
 public:
  Vector2f();
  virtual ~Vector2f();

  Vector2f(const Vector2f& from);

  inline Vector2f& operator=(const Vector2f& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Vector2f& default_instance();

  static inline const Vector2f* internal_default_instance() {
    return reinterpret_cast<const Vector2f*>(
               &_Vector2f_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(Vector2f* other);

  // implements Message ----------------------------------------------

  inline Vector2f* New() const PROTOBUF_FINAL { return New(NULL); }

  Vector2f* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Vector2f& from);
  void MergeFrom(const Vector2f& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Vector2f* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional float x = 1;
  bool has_x() const;
  void clear_x();
  static const int kXFieldNumber = 1;
  float x() const;
  void set_x(float value);

  // optional float y = 2;
  bool has_y() const;
  void clear_y();
  static const int kYFieldNumber = 2;
  float y() const;
  void set_y(float value);

  // @@protoc_insertion_point(class_scope:cartographer.transform.proto.Vector2f)
 private:
  void set_has_x();
  void clear_has_x();
  void set_has_y();
  void clear_has_y();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  float x_;
  float y_;
  friend struct protobuf_cartographer_2ftransform_2fproto_2ftransform_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Vector3d : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:cartographer.transform.proto.Vector3d) */ {
 public:
  Vector3d();
  virtual ~Vector3d();

  Vector3d(const Vector3d& from);

  inline Vector3d& operator=(const Vector3d& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Vector3d& default_instance();

  static inline const Vector3d* internal_default_instance() {
    return reinterpret_cast<const Vector3d*>(
               &_Vector3d_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    2;

  void Swap(Vector3d* other);

  // implements Message ----------------------------------------------

  inline Vector3d* New() const PROTOBUF_FINAL { return New(NULL); }

  Vector3d* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Vector3d& from);
  void MergeFrom(const Vector3d& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Vector3d* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional double x = 1;
  bool has_x() const;
  void clear_x();
  static const int kXFieldNumber = 1;
  double x() const;
  void set_x(double value);

  // optional double y = 2;
  bool has_y() const;
  void clear_y();
  static const int kYFieldNumber = 2;
  double y() const;
  void set_y(double value);

  // optional double z = 3;
  bool has_z() const;
  void clear_z();
  static const int kZFieldNumber = 3;
  double z() const;
  void set_z(double value);

  // @@protoc_insertion_point(class_scope:cartographer.transform.proto.Vector3d)
 private:
  void set_has_x();
  void clear_has_x();
  void set_has_y();
  void clear_has_y();
  void set_has_z();
  void clear_has_z();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  double x_;
  double y_;
  double z_;
  friend struct protobuf_cartographer_2ftransform_2fproto_2ftransform_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Vector3f : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:cartographer.transform.proto.Vector3f) */ {
 public:
  Vector3f();
  virtual ~Vector3f();

  Vector3f(const Vector3f& from);

  inline Vector3f& operator=(const Vector3f& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Vector3f& default_instance();

  static inline const Vector3f* internal_default_instance() {
    return reinterpret_cast<const Vector3f*>(
               &_Vector3f_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    3;

  void Swap(Vector3f* other);

  // implements Message ----------------------------------------------

  inline Vector3f* New() const PROTOBUF_FINAL { return New(NULL); }

  Vector3f* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Vector3f& from);
  void MergeFrom(const Vector3f& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Vector3f* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional float x = 1;
  bool has_x() const;
  void clear_x();
  static const int kXFieldNumber = 1;
  float x() const;
  void set_x(float value);

  // optional float y = 2;
  bool has_y() const;
  void clear_y();
  static const int kYFieldNumber = 2;
  float y() const;
  void set_y(float value);

  // optional float z = 3;
  bool has_z() const;
  void clear_z();
  static const int kZFieldNumber = 3;
  float z() const;
  void set_z(float value);

  // @@protoc_insertion_point(class_scope:cartographer.transform.proto.Vector3f)
 private:
  void set_has_x();
  void clear_has_x();
  void set_has_y();
  void clear_has_y();
  void set_has_z();
  void clear_has_z();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  float x_;
  float y_;
  float z_;
  friend struct protobuf_cartographer_2ftransform_2fproto_2ftransform_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Quaterniond : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:cartographer.transform.proto.Quaterniond) */ {
 public:
  Quaterniond();
  virtual ~Quaterniond();

  Quaterniond(const Quaterniond& from);

  inline Quaterniond& operator=(const Quaterniond& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Quaterniond& default_instance();

  static inline const Quaterniond* internal_default_instance() {
    return reinterpret_cast<const Quaterniond*>(
               &_Quaterniond_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    4;

  void Swap(Quaterniond* other);

  // implements Message ----------------------------------------------

  inline Quaterniond* New() const PROTOBUF_FINAL { return New(NULL); }

  Quaterniond* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Quaterniond& from);
  void MergeFrom(const Quaterniond& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Quaterniond* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional double x = 1;
  bool has_x() const;
  void clear_x();
  static const int kXFieldNumber = 1;
  double x() const;
  void set_x(double value);

  // optional double y = 2;
  bool has_y() const;
  void clear_y();
  static const int kYFieldNumber = 2;
  double y() const;
  void set_y(double value);

  // optional double z = 3;
  bool has_z() const;
  void clear_z();
  static const int kZFieldNumber = 3;
  double z() const;
  void set_z(double value);

  // optional double w = 4;
  bool has_w() const;
  void clear_w();
  static const int kWFieldNumber = 4;
  double w() const;
  void set_w(double value);

  // @@protoc_insertion_point(class_scope:cartographer.transform.proto.Quaterniond)
 private:
  void set_has_x();
  void clear_has_x();
  void set_has_y();
  void clear_has_y();
  void set_has_z();
  void clear_has_z();
  void set_has_w();
  void clear_has_w();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  double x_;
  double y_;
  double z_;
  double w_;
  friend struct protobuf_cartographer_2ftransform_2fproto_2ftransform_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Quaternionf : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:cartographer.transform.proto.Quaternionf) */ {
 public:
  Quaternionf();
  virtual ~Quaternionf();

  Quaternionf(const Quaternionf& from);

  inline Quaternionf& operator=(const Quaternionf& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Quaternionf& default_instance();

  static inline const Quaternionf* internal_default_instance() {
    return reinterpret_cast<const Quaternionf*>(
               &_Quaternionf_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    5;

  void Swap(Quaternionf* other);

  // implements Message ----------------------------------------------

  inline Quaternionf* New() const PROTOBUF_FINAL { return New(NULL); }

  Quaternionf* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Quaternionf& from);
  void MergeFrom(const Quaternionf& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Quaternionf* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional float x = 1;
  bool has_x() const;
  void clear_x();
  static const int kXFieldNumber = 1;
  float x() const;
  void set_x(float value);

  // optional float y = 2;
  bool has_y() const;
  void clear_y();
  static const int kYFieldNumber = 2;
  float y() const;
  void set_y(float value);

  // optional float z = 3;
  bool has_z() const;
  void clear_z();
  static const int kZFieldNumber = 3;
  float z() const;
  void set_z(float value);

  // optional float w = 4;
  bool has_w() const;
  void clear_w();
  static const int kWFieldNumber = 4;
  float w() const;
  void set_w(float value);

  // @@protoc_insertion_point(class_scope:cartographer.transform.proto.Quaternionf)
 private:
  void set_has_x();
  void clear_has_x();
  void set_has_y();
  void clear_has_y();
  void set_has_z();
  void clear_has_z();
  void set_has_w();
  void clear_has_w();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  float x_;
  float y_;
  float z_;
  float w_;
  friend struct protobuf_cartographer_2ftransform_2fproto_2ftransform_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Rigid2d : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:cartographer.transform.proto.Rigid2d) */ {
 public:
  Rigid2d();
  virtual ~Rigid2d();

  Rigid2d(const Rigid2d& from);

  inline Rigid2d& operator=(const Rigid2d& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Rigid2d& default_instance();

  static inline const Rigid2d* internal_default_instance() {
    return reinterpret_cast<const Rigid2d*>(
               &_Rigid2d_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    6;

  void Swap(Rigid2d* other);

  // implements Message ----------------------------------------------

  inline Rigid2d* New() const PROTOBUF_FINAL { return New(NULL); }

  Rigid2d* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Rigid2d& from);
  void MergeFrom(const Rigid2d& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Rigid2d* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .cartographer.transform.proto.Vector2d translation = 1;
  bool has_translation() const;
  void clear_translation();
  static const int kTranslationFieldNumber = 1;
  const ::cartographer::transform::proto::Vector2d& translation() const;
  ::cartographer::transform::proto::Vector2d* mutable_translation();
  ::cartographer::transform::proto::Vector2d* release_translation();
  void set_allocated_translation(::cartographer::transform::proto::Vector2d* translation);

  // optional double rotation = 2;
  bool has_rotation() const;
  void clear_rotation();
  static const int kRotationFieldNumber = 2;
  double rotation() const;
  void set_rotation(double value);

  // @@protoc_insertion_point(class_scope:cartographer.transform.proto.Rigid2d)
 private:
  void set_has_translation();
  void clear_has_translation();
  void set_has_rotation();
  void clear_has_rotation();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::cartographer::transform::proto::Vector2d* translation_;
  double rotation_;
  friend struct protobuf_cartographer_2ftransform_2fproto_2ftransform_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Rigid2f : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:cartographer.transform.proto.Rigid2f) */ {
 public:
  Rigid2f();
  virtual ~Rigid2f();

  Rigid2f(const Rigid2f& from);

  inline Rigid2f& operator=(const Rigid2f& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Rigid2f& default_instance();

  static inline const Rigid2f* internal_default_instance() {
    return reinterpret_cast<const Rigid2f*>(
               &_Rigid2f_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    7;

  void Swap(Rigid2f* other);

  // implements Message ----------------------------------------------

  inline Rigid2f* New() const PROTOBUF_FINAL { return New(NULL); }

  Rigid2f* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Rigid2f& from);
  void MergeFrom(const Rigid2f& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Rigid2f* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .cartographer.transform.proto.Vector2f translation = 1;
  bool has_translation() const;
  void clear_translation();
  static const int kTranslationFieldNumber = 1;
  const ::cartographer::transform::proto::Vector2f& translation() const;
  ::cartographer::transform::proto::Vector2f* mutable_translation();
  ::cartographer::transform::proto::Vector2f* release_translation();
  void set_allocated_translation(::cartographer::transform::proto::Vector2f* translation);

  // optional float rotation = 2;
  bool has_rotation() const;
  void clear_rotation();
  static const int kRotationFieldNumber = 2;
  float rotation() const;
  void set_rotation(float value);

  // @@protoc_insertion_point(class_scope:cartographer.transform.proto.Rigid2f)
 private:
  void set_has_translation();
  void clear_has_translation();
  void set_has_rotation();
  void clear_has_rotation();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::cartographer::transform::proto::Vector2f* translation_;
  float rotation_;
  friend struct protobuf_cartographer_2ftransform_2fproto_2ftransform_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Rigid3d : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:cartographer.transform.proto.Rigid3d) */ {
 public:
  Rigid3d();
  virtual ~Rigid3d();

  Rigid3d(const Rigid3d& from);

  inline Rigid3d& operator=(const Rigid3d& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Rigid3d& default_instance();

  static inline const Rigid3d* internal_default_instance() {
    return reinterpret_cast<const Rigid3d*>(
               &_Rigid3d_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    8;

  void Swap(Rigid3d* other);

  // implements Message ----------------------------------------------

  inline Rigid3d* New() const PROTOBUF_FINAL { return New(NULL); }

  Rigid3d* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Rigid3d& from);
  void MergeFrom(const Rigid3d& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Rigid3d* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .cartographer.transform.proto.Vector3d translation = 1;
  bool has_translation() const;
  void clear_translation();
  static const int kTranslationFieldNumber = 1;
  const ::cartographer::transform::proto::Vector3d& translation() const;
  ::cartographer::transform::proto::Vector3d* mutable_translation();
  ::cartographer::transform::proto::Vector3d* release_translation();
  void set_allocated_translation(::cartographer::transform::proto::Vector3d* translation);

  // optional .cartographer.transform.proto.Quaterniond rotation = 2;
  bool has_rotation() const;
  void clear_rotation();
  static const int kRotationFieldNumber = 2;
  const ::cartographer::transform::proto::Quaterniond& rotation() const;
  ::cartographer::transform::proto::Quaterniond* mutable_rotation();
  ::cartographer::transform::proto::Quaterniond* release_rotation();
  void set_allocated_rotation(::cartographer::transform::proto::Quaterniond* rotation);

  // @@protoc_insertion_point(class_scope:cartographer.transform.proto.Rigid3d)
 private:
  void set_has_translation();
  void clear_has_translation();
  void set_has_rotation();
  void clear_has_rotation();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::cartographer::transform::proto::Vector3d* translation_;
  ::cartographer::transform::proto::Quaterniond* rotation_;
  friend struct protobuf_cartographer_2ftransform_2fproto_2ftransform_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Rigid3f : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:cartographer.transform.proto.Rigid3f) */ {
 public:
  Rigid3f();
  virtual ~Rigid3f();

  Rigid3f(const Rigid3f& from);

  inline Rigid3f& operator=(const Rigid3f& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Rigid3f& default_instance();

  static inline const Rigid3f* internal_default_instance() {
    return reinterpret_cast<const Rigid3f*>(
               &_Rigid3f_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    9;

  void Swap(Rigid3f* other);

  // implements Message ----------------------------------------------

  inline Rigid3f* New() const PROTOBUF_FINAL { return New(NULL); }

  Rigid3f* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Rigid3f& from);
  void MergeFrom(const Rigid3f& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Rigid3f* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .cartographer.transform.proto.Vector3f translation = 1;
  bool has_translation() const;
  void clear_translation();
  static const int kTranslationFieldNumber = 1;
  const ::cartographer::transform::proto::Vector3f& translation() const;
  ::cartographer::transform::proto::Vector3f* mutable_translation();
  ::cartographer::transform::proto::Vector3f* release_translation();
  void set_allocated_translation(::cartographer::transform::proto::Vector3f* translation);

  // optional .cartographer.transform.proto.Quaternionf rotation = 2;
  bool has_rotation() const;
  void clear_rotation();
  static const int kRotationFieldNumber = 2;
  const ::cartographer::transform::proto::Quaternionf& rotation() const;
  ::cartographer::transform::proto::Quaternionf* mutable_rotation();
  ::cartographer::transform::proto::Quaternionf* release_rotation();
  void set_allocated_rotation(::cartographer::transform::proto::Quaternionf* rotation);

  // @@protoc_insertion_point(class_scope:cartographer.transform.proto.Rigid3f)
 private:
  void set_has_translation();
  void clear_has_translation();
  void set_has_rotation();
  void clear_has_rotation();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::cartographer::transform::proto::Vector3f* translation_;
  ::cartographer::transform::proto::Quaternionf* rotation_;
  friend struct protobuf_cartographer_2ftransform_2fproto_2ftransform_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// Vector2d

// optional double x = 1;
inline bool Vector2d::has_x() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Vector2d::set_has_x() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Vector2d::clear_has_x() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Vector2d::clear_x() {
  x_ = 0;
  clear_has_x();
}
inline double Vector2d::x() const {
  // @@protoc_insertion_point(field_get:cartographer.transform.proto.Vector2d.x)
  return x_;
}
inline void Vector2d::set_x(double value) {
  set_has_x();
  x_ = value;
  // @@protoc_insertion_point(field_set:cartographer.transform.proto.Vector2d.x)
}

// optional double y = 2;
inline bool Vector2d::has_y() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Vector2d::set_has_y() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Vector2d::clear_has_y() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Vector2d::clear_y() {
  y_ = 0;
  clear_has_y();
}
inline double Vector2d::y() const {
  // @@protoc_insertion_point(field_get:cartographer.transform.proto.Vector2d.y)
  return y_;
}
inline void Vector2d::set_y(double value) {
  set_has_y();
  y_ = value;
  // @@protoc_insertion_point(field_set:cartographer.transform.proto.Vector2d.y)
}

// -------------------------------------------------------------------

// Vector2f

// optional float x = 1;
inline bool Vector2f::has_x() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Vector2f::set_has_x() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Vector2f::clear_has_x() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Vector2f::clear_x() {
  x_ = 0;
  clear_has_x();
}
inline float Vector2f::x() const {
  // @@protoc_insertion_point(field_get:cartographer.transform.proto.Vector2f.x)
  return x_;
}
inline void Vector2f::set_x(float value) {
  set_has_x();
  x_ = value;
  // @@protoc_insertion_point(field_set:cartographer.transform.proto.Vector2f.x)
}

// optional float y = 2;
inline bool Vector2f::has_y() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Vector2f::set_has_y() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Vector2f::clear_has_y() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Vector2f::clear_y() {
  y_ = 0;
  clear_has_y();
}
inline float Vector2f::y() const {
  // @@protoc_insertion_point(field_get:cartographer.transform.proto.Vector2f.y)
  return y_;
}
inline void Vector2f::set_y(float value) {
  set_has_y();
  y_ = value;
  // @@protoc_insertion_point(field_set:cartographer.transform.proto.Vector2f.y)
}

// -------------------------------------------------------------------

// Vector3d

// optional double x = 1;
inline bool Vector3d::has_x() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Vector3d::set_has_x() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Vector3d::clear_has_x() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Vector3d::clear_x() {
  x_ = 0;
  clear_has_x();
}
inline double Vector3d::x() const {
  // @@protoc_insertion_point(field_get:cartographer.transform.proto.Vector3d.x)
  return x_;
}
inline void Vector3d::set_x(double value) {
  set_has_x();
  x_ = value;
  // @@protoc_insertion_point(field_set:cartographer.transform.proto.Vector3d.x)
}

// optional double y = 2;
inline bool Vector3d::has_y() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Vector3d::set_has_y() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Vector3d::clear_has_y() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Vector3d::clear_y() {
  y_ = 0;
  clear_has_y();
}
inline double Vector3d::y() const {
  // @@protoc_insertion_point(field_get:cartographer.transform.proto.Vector3d.y)
  return y_;
}
inline void Vector3d::set_y(double value) {
  set_has_y();
  y_ = value;
  // @@protoc_insertion_point(field_set:cartographer.transform.proto.Vector3d.y)
}

// optional double z = 3;
inline bool Vector3d::has_z() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Vector3d::set_has_z() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Vector3d::clear_has_z() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Vector3d::clear_z() {
  z_ = 0;
  clear_has_z();
}
inline double Vector3d::z() const {
  // @@protoc_insertion_point(field_get:cartographer.transform.proto.Vector3d.z)
  return z_;
}
inline void Vector3d::set_z(double value) {
  set_has_z();
  z_ = value;
  // @@protoc_insertion_point(field_set:cartographer.transform.proto.Vector3d.z)
}

// -------------------------------------------------------------------

// Vector3f

// optional float x = 1;
inline bool Vector3f::has_x() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Vector3f::set_has_x() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Vector3f::clear_has_x() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Vector3f::clear_x() {
  x_ = 0;
  clear_has_x();
}
inline float Vector3f::x() const {
  // @@protoc_insertion_point(field_get:cartographer.transform.proto.Vector3f.x)
  return x_;
}
inline void Vector3f::set_x(float value) {
  set_has_x();
  x_ = value;
  // @@protoc_insertion_point(field_set:cartographer.transform.proto.Vector3f.x)
}

// optional float y = 2;
inline bool Vector3f::has_y() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Vector3f::set_has_y() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Vector3f::clear_has_y() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Vector3f::clear_y() {
  y_ = 0;
  clear_has_y();
}
inline float Vector3f::y() const {
  // @@protoc_insertion_point(field_get:cartographer.transform.proto.Vector3f.y)
  return y_;
}
inline void Vector3f::set_y(float value) {
  set_has_y();
  y_ = value;
  // @@protoc_insertion_point(field_set:cartographer.transform.proto.Vector3f.y)
}

// optional float z = 3;
inline bool Vector3f::has_z() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Vector3f::set_has_z() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Vector3f::clear_has_z() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Vector3f::clear_z() {
  z_ = 0;
  clear_has_z();
}
inline float Vector3f::z() const {
  // @@protoc_insertion_point(field_get:cartographer.transform.proto.Vector3f.z)
  return z_;
}
inline void Vector3f::set_z(float value) {
  set_has_z();
  z_ = value;
  // @@protoc_insertion_point(field_set:cartographer.transform.proto.Vector3f.z)
}

// -------------------------------------------------------------------

// Quaterniond

// optional double x = 1;
inline bool Quaterniond::has_x() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Quaterniond::set_has_x() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Quaterniond::clear_has_x() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Quaterniond::clear_x() {
  x_ = 0;
  clear_has_x();
}
inline double Quaterniond::x() const {
  // @@protoc_insertion_point(field_get:cartographer.transform.proto.Quaterniond.x)
  return x_;
}
inline void Quaterniond::set_x(double value) {
  set_has_x();
  x_ = value;
  // @@protoc_insertion_point(field_set:cartographer.transform.proto.Quaterniond.x)
}

// optional double y = 2;
inline bool Quaterniond::has_y() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Quaterniond::set_has_y() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Quaterniond::clear_has_y() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Quaterniond::clear_y() {
  y_ = 0;
  clear_has_y();
}
inline double Quaterniond::y() const {
  // @@protoc_insertion_point(field_get:cartographer.transform.proto.Quaterniond.y)
  return y_;
}
inline void Quaterniond::set_y(double value) {
  set_has_y();
  y_ = value;
  // @@protoc_insertion_point(field_set:cartographer.transform.proto.Quaterniond.y)
}

// optional double z = 3;
inline bool Quaterniond::has_z() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Quaterniond::set_has_z() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Quaterniond::clear_has_z() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Quaterniond::clear_z() {
  z_ = 0;
  clear_has_z();
}
inline double Quaterniond::z() const {
  // @@protoc_insertion_point(field_get:cartographer.transform.proto.Quaterniond.z)
  return z_;
}
inline void Quaterniond::set_z(double value) {
  set_has_z();
  z_ = value;
  // @@protoc_insertion_point(field_set:cartographer.transform.proto.Quaterniond.z)
}

// optional double w = 4;
inline bool Quaterniond::has_w() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Quaterniond::set_has_w() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Quaterniond::clear_has_w() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Quaterniond::clear_w() {
  w_ = 0;
  clear_has_w();
}
inline double Quaterniond::w() const {
  // @@protoc_insertion_point(field_get:cartographer.transform.proto.Quaterniond.w)
  return w_;
}
inline void Quaterniond::set_w(double value) {
  set_has_w();
  w_ = value;
  // @@protoc_insertion_point(field_set:cartographer.transform.proto.Quaterniond.w)
}

// -------------------------------------------------------------------

// Quaternionf

// optional float x = 1;
inline bool Quaternionf::has_x() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Quaternionf::set_has_x() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Quaternionf::clear_has_x() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Quaternionf::clear_x() {
  x_ = 0;
  clear_has_x();
}
inline float Quaternionf::x() const {
  // @@protoc_insertion_point(field_get:cartographer.transform.proto.Quaternionf.x)
  return x_;
}
inline void Quaternionf::set_x(float value) {
  set_has_x();
  x_ = value;
  // @@protoc_insertion_point(field_set:cartographer.transform.proto.Quaternionf.x)
}

// optional float y = 2;
inline bool Quaternionf::has_y() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Quaternionf::set_has_y() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Quaternionf::clear_has_y() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Quaternionf::clear_y() {
  y_ = 0;
  clear_has_y();
}
inline float Quaternionf::y() const {
  // @@protoc_insertion_point(field_get:cartographer.transform.proto.Quaternionf.y)
  return y_;
}
inline void Quaternionf::set_y(float value) {
  set_has_y();
  y_ = value;
  // @@protoc_insertion_point(field_set:cartographer.transform.proto.Quaternionf.y)
}

// optional float z = 3;
inline bool Quaternionf::has_z() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Quaternionf::set_has_z() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Quaternionf::clear_has_z() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Quaternionf::clear_z() {
  z_ = 0;
  clear_has_z();
}
inline float Quaternionf::z() const {
  // @@protoc_insertion_point(field_get:cartographer.transform.proto.Quaternionf.z)
  return z_;
}
inline void Quaternionf::set_z(float value) {
  set_has_z();
  z_ = value;
  // @@protoc_insertion_point(field_set:cartographer.transform.proto.Quaternionf.z)
}

// optional float w = 4;
inline bool Quaternionf::has_w() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Quaternionf::set_has_w() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Quaternionf::clear_has_w() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Quaternionf::clear_w() {
  w_ = 0;
  clear_has_w();
}
inline float Quaternionf::w() const {
  // @@protoc_insertion_point(field_get:cartographer.transform.proto.Quaternionf.w)
  return w_;
}
inline void Quaternionf::set_w(float value) {
  set_has_w();
  w_ = value;
  // @@protoc_insertion_point(field_set:cartographer.transform.proto.Quaternionf.w)
}

// -------------------------------------------------------------------

// Rigid2d

// optional .cartographer.transform.proto.Vector2d translation = 1;
inline bool Rigid2d::has_translation() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Rigid2d::set_has_translation() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Rigid2d::clear_has_translation() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Rigid2d::clear_translation() {
  if (translation_ != NULL) translation_->::cartographer::transform::proto::Vector2d::Clear();
  clear_has_translation();
}
inline const ::cartographer::transform::proto::Vector2d& Rigid2d::translation() const {
  // @@protoc_insertion_point(field_get:cartographer.transform.proto.Rigid2d.translation)
  return translation_ != NULL ? *translation_
                         : *::cartographer::transform::proto::Vector2d::internal_default_instance();
}
inline ::cartographer::transform::proto::Vector2d* Rigid2d::mutable_translation() {
  set_has_translation();
  if (translation_ == NULL) {
    translation_ = new ::cartographer::transform::proto::Vector2d;
  }
  // @@protoc_insertion_point(field_mutable:cartographer.transform.proto.Rigid2d.translation)
  return translation_;
}
inline ::cartographer::transform::proto::Vector2d* Rigid2d::release_translation() {
  // @@protoc_insertion_point(field_release:cartographer.transform.proto.Rigid2d.translation)
  clear_has_translation();
  ::cartographer::transform::proto::Vector2d* temp = translation_;
  translation_ = NULL;
  return temp;
}
inline void Rigid2d::set_allocated_translation(::cartographer::transform::proto::Vector2d* translation) {
  delete translation_;
  translation_ = translation;
  if (translation) {
    set_has_translation();
  } else {
    clear_has_translation();
  }
  // @@protoc_insertion_point(field_set_allocated:cartographer.transform.proto.Rigid2d.translation)
}

// optional double rotation = 2;
inline bool Rigid2d::has_rotation() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Rigid2d::set_has_rotation() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Rigid2d::clear_has_rotation() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Rigid2d::clear_rotation() {
  rotation_ = 0;
  clear_has_rotation();
}
inline double Rigid2d::rotation() const {
  // @@protoc_insertion_point(field_get:cartographer.transform.proto.Rigid2d.rotation)
  return rotation_;
}
inline void Rigid2d::set_rotation(double value) {
  set_has_rotation();
  rotation_ = value;
  // @@protoc_insertion_point(field_set:cartographer.transform.proto.Rigid2d.rotation)
}

// -------------------------------------------------------------------

// Rigid2f

// optional .cartographer.transform.proto.Vector2f translation = 1;
inline bool Rigid2f::has_translation() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Rigid2f::set_has_translation() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Rigid2f::clear_has_translation() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Rigid2f::clear_translation() {
  if (translation_ != NULL) translation_->::cartographer::transform::proto::Vector2f::Clear();
  clear_has_translation();
}
inline const ::cartographer::transform::proto::Vector2f& Rigid2f::translation() const {
  // @@protoc_insertion_point(field_get:cartographer.transform.proto.Rigid2f.translation)
  return translation_ != NULL ? *translation_
                         : *::cartographer::transform::proto::Vector2f::internal_default_instance();
}
inline ::cartographer::transform::proto::Vector2f* Rigid2f::mutable_translation() {
  set_has_translation();
  if (translation_ == NULL) {
    translation_ = new ::cartographer::transform::proto::Vector2f;
  }
  // @@protoc_insertion_point(field_mutable:cartographer.transform.proto.Rigid2f.translation)
  return translation_;
}
inline ::cartographer::transform::proto::Vector2f* Rigid2f::release_translation() {
  // @@protoc_insertion_point(field_release:cartographer.transform.proto.Rigid2f.translation)
  clear_has_translation();
  ::cartographer::transform::proto::Vector2f* temp = translation_;
  translation_ = NULL;
  return temp;
}
inline void Rigid2f::set_allocated_translation(::cartographer::transform::proto::Vector2f* translation) {
  delete translation_;
  translation_ = translation;
  if (translation) {
    set_has_translation();
  } else {
    clear_has_translation();
  }
  // @@protoc_insertion_point(field_set_allocated:cartographer.transform.proto.Rigid2f.translation)
}

// optional float rotation = 2;
inline bool Rigid2f::has_rotation() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Rigid2f::set_has_rotation() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Rigid2f::clear_has_rotation() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Rigid2f::clear_rotation() {
  rotation_ = 0;
  clear_has_rotation();
}
inline float Rigid2f::rotation() const {
  // @@protoc_insertion_point(field_get:cartographer.transform.proto.Rigid2f.rotation)
  return rotation_;
}
inline void Rigid2f::set_rotation(float value) {
  set_has_rotation();
  rotation_ = value;
  // @@protoc_insertion_point(field_set:cartographer.transform.proto.Rigid2f.rotation)
}

// -------------------------------------------------------------------

// Rigid3d

// optional .cartographer.transform.proto.Vector3d translation = 1;
inline bool Rigid3d::has_translation() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Rigid3d::set_has_translation() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Rigid3d::clear_has_translation() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Rigid3d::clear_translation() {
  if (translation_ != NULL) translation_->::cartographer::transform::proto::Vector3d::Clear();
  clear_has_translation();
}
inline const ::cartographer::transform::proto::Vector3d& Rigid3d::translation() const {
  // @@protoc_insertion_point(field_get:cartographer.transform.proto.Rigid3d.translation)
  return translation_ != NULL ? *translation_
                         : *::cartographer::transform::proto::Vector3d::internal_default_instance();
}
inline ::cartographer::transform::proto::Vector3d* Rigid3d::mutable_translation() {
  set_has_translation();
  if (translation_ == NULL) {
    translation_ = new ::cartographer::transform::proto::Vector3d;
  }
  // @@protoc_insertion_point(field_mutable:cartographer.transform.proto.Rigid3d.translation)
  return translation_;
}
inline ::cartographer::transform::proto::Vector3d* Rigid3d::release_translation() {
  // @@protoc_insertion_point(field_release:cartographer.transform.proto.Rigid3d.translation)
  clear_has_translation();
  ::cartographer::transform::proto::Vector3d* temp = translation_;
  translation_ = NULL;
  return temp;
}
inline void Rigid3d::set_allocated_translation(::cartographer::transform::proto::Vector3d* translation) {
  delete translation_;
  translation_ = translation;
  if (translation) {
    set_has_translation();
  } else {
    clear_has_translation();
  }
  // @@protoc_insertion_point(field_set_allocated:cartographer.transform.proto.Rigid3d.translation)
}

// optional .cartographer.transform.proto.Quaterniond rotation = 2;
inline bool Rigid3d::has_rotation() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Rigid3d::set_has_rotation() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Rigid3d::clear_has_rotation() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Rigid3d::clear_rotation() {
  if (rotation_ != NULL) rotation_->::cartographer::transform::proto::Quaterniond::Clear();
  clear_has_rotation();
}
inline const ::cartographer::transform::proto::Quaterniond& Rigid3d::rotation() const {
  // @@protoc_insertion_point(field_get:cartographer.transform.proto.Rigid3d.rotation)
  return rotation_ != NULL ? *rotation_
                         : *::cartographer::transform::proto::Quaterniond::internal_default_instance();
}
inline ::cartographer::transform::proto::Quaterniond* Rigid3d::mutable_rotation() {
  set_has_rotation();
  if (rotation_ == NULL) {
    rotation_ = new ::cartographer::transform::proto::Quaterniond;
  }
  // @@protoc_insertion_point(field_mutable:cartographer.transform.proto.Rigid3d.rotation)
  return rotation_;
}
inline ::cartographer::transform::proto::Quaterniond* Rigid3d::release_rotation() {
  // @@protoc_insertion_point(field_release:cartographer.transform.proto.Rigid3d.rotation)
  clear_has_rotation();
  ::cartographer::transform::proto::Quaterniond* temp = rotation_;
  rotation_ = NULL;
  return temp;
}
inline void Rigid3d::set_allocated_rotation(::cartographer::transform::proto::Quaterniond* rotation) {
  delete rotation_;
  rotation_ = rotation;
  if (rotation) {
    set_has_rotation();
  } else {
    clear_has_rotation();
  }
  // @@protoc_insertion_point(field_set_allocated:cartographer.transform.proto.Rigid3d.rotation)
}

// -------------------------------------------------------------------

// Rigid3f

// optional .cartographer.transform.proto.Vector3f translation = 1;
inline bool Rigid3f::has_translation() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Rigid3f::set_has_translation() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Rigid3f::clear_has_translation() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Rigid3f::clear_translation() {
  if (translation_ != NULL) translation_->::cartographer::transform::proto::Vector3f::Clear();
  clear_has_translation();
}
inline const ::cartographer::transform::proto::Vector3f& Rigid3f::translation() const {
  // @@protoc_insertion_point(field_get:cartographer.transform.proto.Rigid3f.translation)
  return translation_ != NULL ? *translation_
                         : *::cartographer::transform::proto::Vector3f::internal_default_instance();
}
inline ::cartographer::transform::proto::Vector3f* Rigid3f::mutable_translation() {
  set_has_translation();
  if (translation_ == NULL) {
    translation_ = new ::cartographer::transform::proto::Vector3f;
  }
  // @@protoc_insertion_point(field_mutable:cartographer.transform.proto.Rigid3f.translation)
  return translation_;
}
inline ::cartographer::transform::proto::Vector3f* Rigid3f::release_translation() {
  // @@protoc_insertion_point(field_release:cartographer.transform.proto.Rigid3f.translation)
  clear_has_translation();
  ::cartographer::transform::proto::Vector3f* temp = translation_;
  translation_ = NULL;
  return temp;
}
inline void Rigid3f::set_allocated_translation(::cartographer::transform::proto::Vector3f* translation) {
  delete translation_;
  translation_ = translation;
  if (translation) {
    set_has_translation();
  } else {
    clear_has_translation();
  }
  // @@protoc_insertion_point(field_set_allocated:cartographer.transform.proto.Rigid3f.translation)
}

// optional .cartographer.transform.proto.Quaternionf rotation = 2;
inline bool Rigid3f::has_rotation() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Rigid3f::set_has_rotation() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Rigid3f::clear_has_rotation() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Rigid3f::clear_rotation() {
  if (rotation_ != NULL) rotation_->::cartographer::transform::proto::Quaternionf::Clear();
  clear_has_rotation();
}
inline const ::cartographer::transform::proto::Quaternionf& Rigid3f::rotation() const {
  // @@protoc_insertion_point(field_get:cartographer.transform.proto.Rigid3f.rotation)
  return rotation_ != NULL ? *rotation_
                         : *::cartographer::transform::proto::Quaternionf::internal_default_instance();
}
inline ::cartographer::transform::proto::Quaternionf* Rigid3f::mutable_rotation() {
  set_has_rotation();
  if (rotation_ == NULL) {
    rotation_ = new ::cartographer::transform::proto::Quaternionf;
  }
  // @@protoc_insertion_point(field_mutable:cartographer.transform.proto.Rigid3f.rotation)
  return rotation_;
}
inline ::cartographer::transform::proto::Quaternionf* Rigid3f::release_rotation() {
  // @@protoc_insertion_point(field_release:cartographer.transform.proto.Rigid3f.rotation)
  clear_has_rotation();
  ::cartographer::transform::proto::Quaternionf* temp = rotation_;
  rotation_ = NULL;
  return temp;
}
inline void Rigid3f::set_allocated_rotation(::cartographer::transform::proto::Quaternionf* rotation) {
  delete rotation_;
  rotation_ = rotation;
  if (rotation) {
    set_has_rotation();
  } else {
    clear_has_rotation();
  }
  // @@protoc_insertion_point(field_set_allocated:cartographer.transform.proto.Rigid3f.rotation)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


}  // namespace proto
}  // namespace transform
}  // namespace cartographer

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_cartographer_2ftransform_2fproto_2ftransform_2eproto__INCLUDED
