// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cartographer/mapping/sparse_pose_graph/proto/constraint_builder_options.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "cartographer/mapping/sparse_pose_graph/proto/constraint_builder_options.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace cartographer {
namespace mapping {
namespace sparse_pose_graph {
namespace proto {
class ConstraintBuilderOptionsDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<ConstraintBuilderOptions> {
} _ConstraintBuilderOptions_default_instance_;

namespace protobuf_cartographer_2fmapping_2fsparse_5fpose_5fgraph_2fproto_2fconstraint_5fbuilder_5foptions_2eproto {


namespace {

::google::protobuf::Metadata file_level_metadata[1];

}  // namespace

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTableField
    const TableStruct::entries[] = {
  {0, 0, 0, ::google::protobuf::internal::kInvalidMask, 0, 0},
};

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::AuxillaryParseTableField
    const TableStruct::aux[] = {
  ::google::protobuf::internal::AuxillaryParseTableField(),
};
PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTable const
    TableStruct::schema[] = {
  { NULL, NULL, 0, -1, -1, false },
};

const ::google::protobuf::uint32 TableStruct::offsets[] = {
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ConstraintBuilderOptions, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ConstraintBuilderOptions, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ConstraintBuilderOptions, sampling_ratio_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ConstraintBuilderOptions, max_constraint_distance_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ConstraintBuilderOptions, adaptive_voxel_filter_options_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ConstraintBuilderOptions, min_score_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ConstraintBuilderOptions, global_localization_min_score_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ConstraintBuilderOptions, loop_closure_translation_weight_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ConstraintBuilderOptions, loop_closure_rotation_weight_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ConstraintBuilderOptions, log_matches_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ConstraintBuilderOptions, fast_correlative_scan_matcher_options_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ConstraintBuilderOptions, ceres_scan_matcher_options_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ConstraintBuilderOptions, fast_correlative_scan_matcher_options_3d_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ConstraintBuilderOptions, high_resolution_adaptive_voxel_filter_options_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ConstraintBuilderOptions, low_resolution_adaptive_voxel_filter_options_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ConstraintBuilderOptions, ceres_scan_matcher_options_3d_),
  7,
  8,
  0,
  9,
  10,
  11,
  12,
  13,
  1,
  3,
  2,
  5,
  6,
  4,
};

static const ::google::protobuf::internal::MigrationSchema schemas[] = {
  { 0, 19, sizeof(ConstraintBuilderOptions)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&_ConstraintBuilderOptions_default_instance_),
};

namespace {

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "cartographer/mapping/sparse_pose_graph/proto/constraint_builder_options.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

}  // namespace

void TableStruct::Shutdown() {
  _ConstraintBuilderOptions_default_instance_.Shutdown();
  delete file_level_metadata[0].reflection;
}

void TableStruct::InitDefaultsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  ::cartographer::sensor::proto::protobuf_cartographer_2fsensor_2fproto_2fadaptive_5fvoxel_5ffilter_5foptions_2eproto::InitDefaults();
  ::cartographer::mapping_2d::scan_matching::proto::protobuf_cartographer_2fmapping_5f2d_2fscan_5fmatching_2fproto_2fceres_5fscan_5fmatcher_5foptions_2eproto::InitDefaults();
  ::cartographer::mapping_2d::scan_matching::proto::protobuf_cartographer_2fmapping_5f2d_2fscan_5fmatching_2fproto_2ffast_5fcorrelative_5fscan_5fmatcher_5foptions_2eproto::InitDefaults();
  ::cartographer::mapping_3d::scan_matching::proto::protobuf_cartographer_2fmapping_5f3d_2fscan_5fmatching_2fproto_2fceres_5fscan_5fmatcher_5foptions_2eproto::InitDefaults();
  ::cartographer::mapping_3d::scan_matching::proto::protobuf_cartographer_2fmapping_5f3d_2fscan_5fmatching_2fproto_2ffast_5fcorrelative_5fscan_5fmatcher_5foptions_2eproto::InitDefaults();
  _ConstraintBuilderOptions_default_instance_.DefaultConstruct();
  _ConstraintBuilderOptions_default_instance_.get_mutable()->adaptive_voxel_filter_options_ = const_cast< ::cartographer::sensor::proto::AdaptiveVoxelFilterOptions*>(
      ::cartographer::sensor::proto::AdaptiveVoxelFilterOptions::internal_default_instance());
  _ConstraintBuilderOptions_default_instance_.get_mutable()->fast_correlative_scan_matcher_options_ = const_cast< ::cartographer::mapping_2d::scan_matching::proto::FastCorrelativeScanMatcherOptions*>(
      ::cartographer::mapping_2d::scan_matching::proto::FastCorrelativeScanMatcherOptions::internal_default_instance());
  _ConstraintBuilderOptions_default_instance_.get_mutable()->ceres_scan_matcher_options_ = const_cast< ::cartographer::mapping_2d::scan_matching::proto::CeresScanMatcherOptions*>(
      ::cartographer::mapping_2d::scan_matching::proto::CeresScanMatcherOptions::internal_default_instance());
  _ConstraintBuilderOptions_default_instance_.get_mutable()->fast_correlative_scan_matcher_options_3d_ = const_cast< ::cartographer::mapping_3d::scan_matching::proto::FastCorrelativeScanMatcherOptions*>(
      ::cartographer::mapping_3d::scan_matching::proto::FastCorrelativeScanMatcherOptions::internal_default_instance());
  _ConstraintBuilderOptions_default_instance_.get_mutable()->high_resolution_adaptive_voxel_filter_options_ = const_cast< ::cartographer::sensor::proto::AdaptiveVoxelFilterOptions*>(
      ::cartographer::sensor::proto::AdaptiveVoxelFilterOptions::internal_default_instance());
  _ConstraintBuilderOptions_default_instance_.get_mutable()->low_resolution_adaptive_voxel_filter_options_ = const_cast< ::cartographer::sensor::proto::AdaptiveVoxelFilterOptions*>(
      ::cartographer::sensor::proto::AdaptiveVoxelFilterOptions::internal_default_instance());
  _ConstraintBuilderOptions_default_instance_.get_mutable()->ceres_scan_matcher_options_3d_ = const_cast< ::cartographer::mapping_3d::scan_matching::proto::CeresScanMatcherOptions*>(
      ::cartographer::mapping_3d::scan_matching::proto::CeresScanMatcherOptions::internal_default_instance());
}

void InitDefaults() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &TableStruct::InitDefaultsImpl);
}
void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] = {
      "\nMcartographer/mapping/sparse_pose_graph"
      "/proto/constraint_builder_options.proto\022"
      ",cartographer.mapping.sparse_pose_graph."
      "proto\032=cartographer/sensor/proto/adaptiv"
      "e_voxel_filter_options.proto\032Lcartograph"
      "er/mapping_2d/scan_matching/proto/ceres_"
      "scan_matcher_options.proto\032Wcartographer"
      "/mapping_2d/scan_matching/proto/fast_cor"
      "relative_scan_matcher_options.proto\032Lcar"
      "tographer/mapping_3d/scan_matching/proto"
      "/ceres_scan_matcher_options.proto\032Wcarto"
      "grapher/mapping_3d/scan_matching/proto/f"
      "ast_correlative_scan_matcher_options.pro"
      "to\"\203\010\n\030ConstraintBuilderOptions\022\026\n\016sampl"
      "ing_ratio\030\001 \001(\001\022\037\n\027max_constraint_distan"
      "ce\030\002 \001(\001\022\\\n\035adaptive_voxel_filter_option"
      "s\030\003 \001(\01325.cartographer.sensor.proto.Adap"
      "tiveVoxelFilterOptions\022\021\n\tmin_score\030\004 \001("
      "\001\022%\n\035global_localization_min_score\030\005 \001(\001"
      "\022\'\n\037loop_closure_translation_weight\030\r \001("
      "\001\022$\n\034loop_closure_rotation_weight\030\016 \001(\001\022"
      "\023\n\013log_matches\030\010 \001(\010\022}\n%fast_correlative"
      "_scan_matcher_options\030\t \001(\0132N.cartograph"
      "er.mapping_2d.scan_matching.proto.FastCo"
      "rrelativeScanMatcherOptions\022h\n\032ceres_sca"
      "n_matcher_options\030\013 \001(\0132D.cartographer.m"
      "apping_2d.scan_matching.proto.CeresScanM"
      "atcherOptions\022\200\001\n(fast_correlative_scan_"
      "matcher_options_3d\030\n \001(\0132N.cartographer."
      "mapping_3d.scan_matching.proto.FastCorre"
      "lativeScanMatcherOptions\022l\n-high_resolut"
      "ion_adaptive_voxel_filter_options\030\017 \001(\0132"
      "5.cartographer.sensor.proto.AdaptiveVoxe"
      "lFilterOptions\022k\n,low_resolution_adaptiv"
      "e_voxel_filter_options\030\020 \001(\01325.cartograp"
      "her.sensor.proto.AdaptiveVoxelFilterOpti"
      "ons\022k\n\035ceres_scan_matcher_options_3d\030\014 \001"
      "(\0132D.cartographer.mapping_3d.scan_matchi"
      "ng.proto.CeresScanMatcherOptions"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 1552);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "cartographer/mapping/sparse_pose_graph/proto/constraint_builder_options.proto", &protobuf_RegisterTypes);
  ::cartographer::sensor::proto::protobuf_cartographer_2fsensor_2fproto_2fadaptive_5fvoxel_5ffilter_5foptions_2eproto::AddDescriptors();
  ::cartographer::mapping_2d::scan_matching::proto::protobuf_cartographer_2fmapping_5f2d_2fscan_5fmatching_2fproto_2fceres_5fscan_5fmatcher_5foptions_2eproto::AddDescriptors();
  ::cartographer::mapping_2d::scan_matching::proto::protobuf_cartographer_2fmapping_5f2d_2fscan_5fmatching_2fproto_2ffast_5fcorrelative_5fscan_5fmatcher_5foptions_2eproto::AddDescriptors();
  ::cartographer::mapping_3d::scan_matching::proto::protobuf_cartographer_2fmapping_5f3d_2fscan_5fmatching_2fproto_2fceres_5fscan_5fmatcher_5foptions_2eproto::AddDescriptors();
  ::cartographer::mapping_3d::scan_matching::proto::protobuf_cartographer_2fmapping_5f3d_2fscan_5fmatching_2fproto_2ffast_5fcorrelative_5fscan_5fmatcher_5foptions_2eproto::AddDescriptors();
  ::google::protobuf::internal::OnShutdown(&TableStruct::Shutdown);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;

}  // namespace protobuf_cartographer_2fmapping_2fsparse_5fpose_5fgraph_2fproto_2fconstraint_5fbuilder_5foptions_2eproto


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ConstraintBuilderOptions::kSamplingRatioFieldNumber;
const int ConstraintBuilderOptions::kMaxConstraintDistanceFieldNumber;
const int ConstraintBuilderOptions::kAdaptiveVoxelFilterOptionsFieldNumber;
const int ConstraintBuilderOptions::kMinScoreFieldNumber;
const int ConstraintBuilderOptions::kGlobalLocalizationMinScoreFieldNumber;
const int ConstraintBuilderOptions::kLoopClosureTranslationWeightFieldNumber;
const int ConstraintBuilderOptions::kLoopClosureRotationWeightFieldNumber;
const int ConstraintBuilderOptions::kLogMatchesFieldNumber;
const int ConstraintBuilderOptions::kFastCorrelativeScanMatcherOptionsFieldNumber;
const int ConstraintBuilderOptions::kCeresScanMatcherOptionsFieldNumber;
const int ConstraintBuilderOptions::kFastCorrelativeScanMatcherOptions3DFieldNumber;
const int ConstraintBuilderOptions::kHighResolutionAdaptiveVoxelFilterOptionsFieldNumber;
const int ConstraintBuilderOptions::kLowResolutionAdaptiveVoxelFilterOptionsFieldNumber;
const int ConstraintBuilderOptions::kCeresScanMatcherOptions3DFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ConstraintBuilderOptions::ConstraintBuilderOptions()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_cartographer_2fmapping_2fsparse_5fpose_5fgraph_2fproto_2fconstraint_5fbuilder_5foptions_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:cartographer.mapping.sparse_pose_graph.proto.ConstraintBuilderOptions)
}
ConstraintBuilderOptions::ConstraintBuilderOptions(const ConstraintBuilderOptions& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.has_adaptive_voxel_filter_options()) {
    adaptive_voxel_filter_options_ = new ::cartographer::sensor::proto::AdaptiveVoxelFilterOptions(*from.adaptive_voxel_filter_options_);
  } else {
    adaptive_voxel_filter_options_ = NULL;
  }
  if (from.has_fast_correlative_scan_matcher_options()) {
    fast_correlative_scan_matcher_options_ = new ::cartographer::mapping_2d::scan_matching::proto::FastCorrelativeScanMatcherOptions(*from.fast_correlative_scan_matcher_options_);
  } else {
    fast_correlative_scan_matcher_options_ = NULL;
  }
  if (from.has_fast_correlative_scan_matcher_options_3d()) {
    fast_correlative_scan_matcher_options_3d_ = new ::cartographer::mapping_3d::scan_matching::proto::FastCorrelativeScanMatcherOptions(*from.fast_correlative_scan_matcher_options_3d_);
  } else {
    fast_correlative_scan_matcher_options_3d_ = NULL;
  }
  if (from.has_ceres_scan_matcher_options()) {
    ceres_scan_matcher_options_ = new ::cartographer::mapping_2d::scan_matching::proto::CeresScanMatcherOptions(*from.ceres_scan_matcher_options_);
  } else {
    ceres_scan_matcher_options_ = NULL;
  }
  if (from.has_ceres_scan_matcher_options_3d()) {
    ceres_scan_matcher_options_3d_ = new ::cartographer::mapping_3d::scan_matching::proto::CeresScanMatcherOptions(*from.ceres_scan_matcher_options_3d_);
  } else {
    ceres_scan_matcher_options_3d_ = NULL;
  }
  if (from.has_high_resolution_adaptive_voxel_filter_options()) {
    high_resolution_adaptive_voxel_filter_options_ = new ::cartographer::sensor::proto::AdaptiveVoxelFilterOptions(*from.high_resolution_adaptive_voxel_filter_options_);
  } else {
    high_resolution_adaptive_voxel_filter_options_ = NULL;
  }
  if (from.has_low_resolution_adaptive_voxel_filter_options()) {
    low_resolution_adaptive_voxel_filter_options_ = new ::cartographer::sensor::proto::AdaptiveVoxelFilterOptions(*from.low_resolution_adaptive_voxel_filter_options_);
  } else {
    low_resolution_adaptive_voxel_filter_options_ = NULL;
  }
  ::memcpy(&sampling_ratio_, &from.sampling_ratio_,
    static_cast<size_t>(reinterpret_cast<char*>(&log_matches_) -
    reinterpret_cast<char*>(&sampling_ratio_)) + sizeof(log_matches_));
  // @@protoc_insertion_point(copy_constructor:cartographer.mapping.sparse_pose_graph.proto.ConstraintBuilderOptions)
}

void ConstraintBuilderOptions::SharedCtor() {
  _cached_size_ = 0;
  ::memset(&adaptive_voxel_filter_options_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&log_matches_) -
      reinterpret_cast<char*>(&adaptive_voxel_filter_options_)) + sizeof(log_matches_));
}

ConstraintBuilderOptions::~ConstraintBuilderOptions() {
  // @@protoc_insertion_point(destructor:cartographer.mapping.sparse_pose_graph.proto.ConstraintBuilderOptions)
  SharedDtor();
}

void ConstraintBuilderOptions::SharedDtor() {
  if (this != internal_default_instance()) {
    delete adaptive_voxel_filter_options_;
  }
  if (this != internal_default_instance()) {
    delete fast_correlative_scan_matcher_options_;
  }
  if (this != internal_default_instance()) {
    delete fast_correlative_scan_matcher_options_3d_;
  }
  if (this != internal_default_instance()) {
    delete ceres_scan_matcher_options_;
  }
  if (this != internal_default_instance()) {
    delete ceres_scan_matcher_options_3d_;
  }
  if (this != internal_default_instance()) {
    delete high_resolution_adaptive_voxel_filter_options_;
  }
  if (this != internal_default_instance()) {
    delete low_resolution_adaptive_voxel_filter_options_;
  }
}

void ConstraintBuilderOptions::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ConstraintBuilderOptions::descriptor() {
  protobuf_cartographer_2fmapping_2fsparse_5fpose_5fgraph_2fproto_2fconstraint_5fbuilder_5foptions_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_cartographer_2fmapping_2fsparse_5fpose_5fgraph_2fproto_2fconstraint_5fbuilder_5foptions_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const ConstraintBuilderOptions& ConstraintBuilderOptions::default_instance() {
  protobuf_cartographer_2fmapping_2fsparse_5fpose_5fgraph_2fproto_2fconstraint_5fbuilder_5foptions_2eproto::InitDefaults();
  return *internal_default_instance();
}

ConstraintBuilderOptions* ConstraintBuilderOptions::New(::google::protobuf::Arena* arena) const {
  ConstraintBuilderOptions* n = new ConstraintBuilderOptions;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void ConstraintBuilderOptions::Clear() {
// @@protoc_insertion_point(message_clear_start:cartographer.mapping.sparse_pose_graph.proto.ConstraintBuilderOptions)
  if (_has_bits_[0 / 32] & 127u) {
    if (has_adaptive_voxel_filter_options()) {
      GOOGLE_DCHECK(adaptive_voxel_filter_options_ != NULL);
      adaptive_voxel_filter_options_->::cartographer::sensor::proto::AdaptiveVoxelFilterOptions::Clear();
    }
    if (has_fast_correlative_scan_matcher_options()) {
      GOOGLE_DCHECK(fast_correlative_scan_matcher_options_ != NULL);
      fast_correlative_scan_matcher_options_->::cartographer::mapping_2d::scan_matching::proto::FastCorrelativeScanMatcherOptions::Clear();
    }
    if (has_fast_correlative_scan_matcher_options_3d()) {
      GOOGLE_DCHECK(fast_correlative_scan_matcher_options_3d_ != NULL);
      fast_correlative_scan_matcher_options_3d_->::cartographer::mapping_3d::scan_matching::proto::FastCorrelativeScanMatcherOptions::Clear();
    }
    if (has_ceres_scan_matcher_options()) {
      GOOGLE_DCHECK(ceres_scan_matcher_options_ != NULL);
      ceres_scan_matcher_options_->::cartographer::mapping_2d::scan_matching::proto::CeresScanMatcherOptions::Clear();
    }
    if (has_ceres_scan_matcher_options_3d()) {
      GOOGLE_DCHECK(ceres_scan_matcher_options_3d_ != NULL);
      ceres_scan_matcher_options_3d_->::cartographer::mapping_3d::scan_matching::proto::CeresScanMatcherOptions::Clear();
    }
    if (has_high_resolution_adaptive_voxel_filter_options()) {
      GOOGLE_DCHECK(high_resolution_adaptive_voxel_filter_options_ != NULL);
      high_resolution_adaptive_voxel_filter_options_->::cartographer::sensor::proto::AdaptiveVoxelFilterOptions::Clear();
    }
    if (has_low_resolution_adaptive_voxel_filter_options()) {
      GOOGLE_DCHECK(low_resolution_adaptive_voxel_filter_options_ != NULL);
      low_resolution_adaptive_voxel_filter_options_->::cartographer::sensor::proto::AdaptiveVoxelFilterOptions::Clear();
    }
  }
  sampling_ratio_ = 0;
  if (_has_bits_[8 / 32] & 16128u) {
    ::memset(&max_constraint_distance_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&log_matches_) -
        reinterpret_cast<char*>(&max_constraint_distance_)) + sizeof(log_matches_));
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool ConstraintBuilderOptions::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:cartographer.mapping.sparse_pose_graph.proto.ConstraintBuilderOptions)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(16383u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional double sampling_ratio = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(9u)) {
          set_has_sampling_ratio();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &sampling_ratio_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional double max_constraint_distance = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(17u)) {
          set_has_max_constraint_distance();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &max_constraint_distance_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional .cartographer.sensor.proto.AdaptiveVoxelFilterOptions adaptive_voxel_filter_options = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_adaptive_voxel_filter_options()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional double min_score = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(33u)) {
          set_has_min_score();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &min_score_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional double global_localization_min_score = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(41u)) {
          set_has_global_localization_min_score();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &global_localization_min_score_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional bool log_matches = 8;
      case 8: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(64u)) {
          set_has_log_matches();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &log_matches_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional .cartographer.mapping_2d.scan_matching.proto.FastCorrelativeScanMatcherOptions fast_correlative_scan_matcher_options = 9;
      case 9: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(74u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_fast_correlative_scan_matcher_options()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional .cartographer.mapping_3d.scan_matching.proto.FastCorrelativeScanMatcherOptions fast_correlative_scan_matcher_options_3d = 10;
      case 10: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(82u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_fast_correlative_scan_matcher_options_3d()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional .cartographer.mapping_2d.scan_matching.proto.CeresScanMatcherOptions ceres_scan_matcher_options = 11;
      case 11: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(90u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_ceres_scan_matcher_options()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional .cartographer.mapping_3d.scan_matching.proto.CeresScanMatcherOptions ceres_scan_matcher_options_3d = 12;
      case 12: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(98u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_ceres_scan_matcher_options_3d()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional double loop_closure_translation_weight = 13;
      case 13: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(105u)) {
          set_has_loop_closure_translation_weight();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &loop_closure_translation_weight_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional double loop_closure_rotation_weight = 14;
      case 14: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(113u)) {
          set_has_loop_closure_rotation_weight();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &loop_closure_rotation_weight_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional .cartographer.sensor.proto.AdaptiveVoxelFilterOptions high_resolution_adaptive_voxel_filter_options = 15;
      case 15: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(122u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_high_resolution_adaptive_voxel_filter_options()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional .cartographer.sensor.proto.AdaptiveVoxelFilterOptions low_resolution_adaptive_voxel_filter_options = 16;
      case 16: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(130u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_low_resolution_adaptive_voxel_filter_options()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:cartographer.mapping.sparse_pose_graph.proto.ConstraintBuilderOptions)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:cartographer.mapping.sparse_pose_graph.proto.ConstraintBuilderOptions)
  return false;
#undef DO_
}

void ConstraintBuilderOptions::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:cartographer.mapping.sparse_pose_graph.proto.ConstraintBuilderOptions)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional double sampling_ratio = 1;
  if (cached_has_bits & 0x00000080u) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(1, this->sampling_ratio(), output);
  }

  // optional double max_constraint_distance = 2;
  if (cached_has_bits & 0x00000100u) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(2, this->max_constraint_distance(), output);
  }

  // optional .cartographer.sensor.proto.AdaptiveVoxelFilterOptions adaptive_voxel_filter_options = 3;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, *this->adaptive_voxel_filter_options_, output);
  }

  // optional double min_score = 4;
  if (cached_has_bits & 0x00000200u) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(4, this->min_score(), output);
  }

  // optional double global_localization_min_score = 5;
  if (cached_has_bits & 0x00000400u) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(5, this->global_localization_min_score(), output);
  }

  // optional bool log_matches = 8;
  if (cached_has_bits & 0x00002000u) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(8, this->log_matches(), output);
  }

  // optional .cartographer.mapping_2d.scan_matching.proto.FastCorrelativeScanMatcherOptions fast_correlative_scan_matcher_options = 9;
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      9, *this->fast_correlative_scan_matcher_options_, output);
  }

  // optional .cartographer.mapping_3d.scan_matching.proto.FastCorrelativeScanMatcherOptions fast_correlative_scan_matcher_options_3d = 10;
  if (cached_has_bits & 0x00000004u) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      10, *this->fast_correlative_scan_matcher_options_3d_, output);
  }

  // optional .cartographer.mapping_2d.scan_matching.proto.CeresScanMatcherOptions ceres_scan_matcher_options = 11;
  if (cached_has_bits & 0x00000008u) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      11, *this->ceres_scan_matcher_options_, output);
  }

  // optional .cartographer.mapping_3d.scan_matching.proto.CeresScanMatcherOptions ceres_scan_matcher_options_3d = 12;
  if (cached_has_bits & 0x00000010u) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      12, *this->ceres_scan_matcher_options_3d_, output);
  }

  // optional double loop_closure_translation_weight = 13;
  if (cached_has_bits & 0x00000800u) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(13, this->loop_closure_translation_weight(), output);
  }

  // optional double loop_closure_rotation_weight = 14;
  if (cached_has_bits & 0x00001000u) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(14, this->loop_closure_rotation_weight(), output);
  }

  // optional .cartographer.sensor.proto.AdaptiveVoxelFilterOptions high_resolution_adaptive_voxel_filter_options = 15;
  if (cached_has_bits & 0x00000020u) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      15, *this->high_resolution_adaptive_voxel_filter_options_, output);
  }

  // optional .cartographer.sensor.proto.AdaptiveVoxelFilterOptions low_resolution_adaptive_voxel_filter_options = 16;
  if (cached_has_bits & 0x00000040u) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      16, *this->low_resolution_adaptive_voxel_filter_options_, output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:cartographer.mapping.sparse_pose_graph.proto.ConstraintBuilderOptions)
}

::google::protobuf::uint8* ConstraintBuilderOptions::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:cartographer.mapping.sparse_pose_graph.proto.ConstraintBuilderOptions)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional double sampling_ratio = 1;
  if (cached_has_bits & 0x00000080u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(1, this->sampling_ratio(), target);
  }

  // optional double max_constraint_distance = 2;
  if (cached_has_bits & 0x00000100u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(2, this->max_constraint_distance(), target);
  }

  // optional .cartographer.sensor.proto.AdaptiveVoxelFilterOptions adaptive_voxel_filter_options = 3;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        3, *this->adaptive_voxel_filter_options_, deterministic, target);
  }

  // optional double min_score = 4;
  if (cached_has_bits & 0x00000200u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(4, this->min_score(), target);
  }

  // optional double global_localization_min_score = 5;
  if (cached_has_bits & 0x00000400u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(5, this->global_localization_min_score(), target);
  }

  // optional bool log_matches = 8;
  if (cached_has_bits & 0x00002000u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(8, this->log_matches(), target);
  }

  // optional .cartographer.mapping_2d.scan_matching.proto.FastCorrelativeScanMatcherOptions fast_correlative_scan_matcher_options = 9;
  if (cached_has_bits & 0x00000002u) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        9, *this->fast_correlative_scan_matcher_options_, deterministic, target);
  }

  // optional .cartographer.mapping_3d.scan_matching.proto.FastCorrelativeScanMatcherOptions fast_correlative_scan_matcher_options_3d = 10;
  if (cached_has_bits & 0x00000004u) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        10, *this->fast_correlative_scan_matcher_options_3d_, deterministic, target);
  }

  // optional .cartographer.mapping_2d.scan_matching.proto.CeresScanMatcherOptions ceres_scan_matcher_options = 11;
  if (cached_has_bits & 0x00000008u) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        11, *this->ceres_scan_matcher_options_, deterministic, target);
  }

  // optional .cartographer.mapping_3d.scan_matching.proto.CeresScanMatcherOptions ceres_scan_matcher_options_3d = 12;
  if (cached_has_bits & 0x00000010u) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        12, *this->ceres_scan_matcher_options_3d_, deterministic, target);
  }

  // optional double loop_closure_translation_weight = 13;
  if (cached_has_bits & 0x00000800u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(13, this->loop_closure_translation_weight(), target);
  }

  // optional double loop_closure_rotation_weight = 14;
  if (cached_has_bits & 0x00001000u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(14, this->loop_closure_rotation_weight(), target);
  }

  // optional .cartographer.sensor.proto.AdaptiveVoxelFilterOptions high_resolution_adaptive_voxel_filter_options = 15;
  if (cached_has_bits & 0x00000020u) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        15, *this->high_resolution_adaptive_voxel_filter_options_, deterministic, target);
  }

  // optional .cartographer.sensor.proto.AdaptiveVoxelFilterOptions low_resolution_adaptive_voxel_filter_options = 16;
  if (cached_has_bits & 0x00000040u) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        16, *this->low_resolution_adaptive_voxel_filter_options_, deterministic, target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:cartographer.mapping.sparse_pose_graph.proto.ConstraintBuilderOptions)
  return target;
}

size_t ConstraintBuilderOptions::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:cartographer.mapping.sparse_pose_graph.proto.ConstraintBuilderOptions)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  if (_has_bits_[0 / 32] & 255u) {
    // optional .cartographer.sensor.proto.AdaptiveVoxelFilterOptions adaptive_voxel_filter_options = 3;
    if (has_adaptive_voxel_filter_options()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          *this->adaptive_voxel_filter_options_);
    }

    // optional .cartographer.mapping_2d.scan_matching.proto.FastCorrelativeScanMatcherOptions fast_correlative_scan_matcher_options = 9;
    if (has_fast_correlative_scan_matcher_options()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          *this->fast_correlative_scan_matcher_options_);
    }

    // optional .cartographer.mapping_3d.scan_matching.proto.FastCorrelativeScanMatcherOptions fast_correlative_scan_matcher_options_3d = 10;
    if (has_fast_correlative_scan_matcher_options_3d()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          *this->fast_correlative_scan_matcher_options_3d_);
    }

    // optional .cartographer.mapping_2d.scan_matching.proto.CeresScanMatcherOptions ceres_scan_matcher_options = 11;
    if (has_ceres_scan_matcher_options()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          *this->ceres_scan_matcher_options_);
    }

    // optional .cartographer.mapping_3d.scan_matching.proto.CeresScanMatcherOptions ceres_scan_matcher_options_3d = 12;
    if (has_ceres_scan_matcher_options_3d()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          *this->ceres_scan_matcher_options_3d_);
    }

    // optional .cartographer.sensor.proto.AdaptiveVoxelFilterOptions high_resolution_adaptive_voxel_filter_options = 15;
    if (has_high_resolution_adaptive_voxel_filter_options()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          *this->high_resolution_adaptive_voxel_filter_options_);
    }

    // optional .cartographer.sensor.proto.AdaptiveVoxelFilterOptions low_resolution_adaptive_voxel_filter_options = 16;
    if (has_low_resolution_adaptive_voxel_filter_options()) {
      total_size += 2 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          *this->low_resolution_adaptive_voxel_filter_options_);
    }

    // optional double sampling_ratio = 1;
    if (has_sampling_ratio()) {
      total_size += 1 + 8;
    }

  }
  if (_has_bits_[8 / 32] & 16128u) {
    // optional double max_constraint_distance = 2;
    if (has_max_constraint_distance()) {
      total_size += 1 + 8;
    }

    // optional double min_score = 4;
    if (has_min_score()) {
      total_size += 1 + 8;
    }

    // optional double global_localization_min_score = 5;
    if (has_global_localization_min_score()) {
      total_size += 1 + 8;
    }

    // optional double loop_closure_translation_weight = 13;
    if (has_loop_closure_translation_weight()) {
      total_size += 1 + 8;
    }

    // optional double loop_closure_rotation_weight = 14;
    if (has_loop_closure_rotation_weight()) {
      total_size += 1 + 8;
    }

    // optional bool log_matches = 8;
    if (has_log_matches()) {
      total_size += 1 + 1;
    }

  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ConstraintBuilderOptions::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:cartographer.mapping.sparse_pose_graph.proto.ConstraintBuilderOptions)
  GOOGLE_DCHECK_NE(&from, this);
  const ConstraintBuilderOptions* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const ConstraintBuilderOptions>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:cartographer.mapping.sparse_pose_graph.proto.ConstraintBuilderOptions)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:cartographer.mapping.sparse_pose_graph.proto.ConstraintBuilderOptions)
    MergeFrom(*source);
  }
}

void ConstraintBuilderOptions::MergeFrom(const ConstraintBuilderOptions& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:cartographer.mapping.sparse_pose_graph.proto.ConstraintBuilderOptions)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 255u) {
    if (cached_has_bits & 0x00000001u) {
      mutable_adaptive_voxel_filter_options()->::cartographer::sensor::proto::AdaptiveVoxelFilterOptions::MergeFrom(from.adaptive_voxel_filter_options());
    }
    if (cached_has_bits & 0x00000002u) {
      mutable_fast_correlative_scan_matcher_options()->::cartographer::mapping_2d::scan_matching::proto::FastCorrelativeScanMatcherOptions::MergeFrom(from.fast_correlative_scan_matcher_options());
    }
    if (cached_has_bits & 0x00000004u) {
      mutable_fast_correlative_scan_matcher_options_3d()->::cartographer::mapping_3d::scan_matching::proto::FastCorrelativeScanMatcherOptions::MergeFrom(from.fast_correlative_scan_matcher_options_3d());
    }
    if (cached_has_bits & 0x00000008u) {
      mutable_ceres_scan_matcher_options()->::cartographer::mapping_2d::scan_matching::proto::CeresScanMatcherOptions::MergeFrom(from.ceres_scan_matcher_options());
    }
    if (cached_has_bits & 0x00000010u) {
      mutable_ceres_scan_matcher_options_3d()->::cartographer::mapping_3d::scan_matching::proto::CeresScanMatcherOptions::MergeFrom(from.ceres_scan_matcher_options_3d());
    }
    if (cached_has_bits & 0x00000020u) {
      mutable_high_resolution_adaptive_voxel_filter_options()->::cartographer::sensor::proto::AdaptiveVoxelFilterOptions::MergeFrom(from.high_resolution_adaptive_voxel_filter_options());
    }
    if (cached_has_bits & 0x00000040u) {
      mutable_low_resolution_adaptive_voxel_filter_options()->::cartographer::sensor::proto::AdaptiveVoxelFilterOptions::MergeFrom(from.low_resolution_adaptive_voxel_filter_options());
    }
    if (cached_has_bits & 0x00000080u) {
      sampling_ratio_ = from.sampling_ratio_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
  if (cached_has_bits & 16128u) {
    if (cached_has_bits & 0x00000100u) {
      max_constraint_distance_ = from.max_constraint_distance_;
    }
    if (cached_has_bits & 0x00000200u) {
      min_score_ = from.min_score_;
    }
    if (cached_has_bits & 0x00000400u) {
      global_localization_min_score_ = from.global_localization_min_score_;
    }
    if (cached_has_bits & 0x00000800u) {
      loop_closure_translation_weight_ = from.loop_closure_translation_weight_;
    }
    if (cached_has_bits & 0x00001000u) {
      loop_closure_rotation_weight_ = from.loop_closure_rotation_weight_;
    }
    if (cached_has_bits & 0x00002000u) {
      log_matches_ = from.log_matches_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void ConstraintBuilderOptions::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:cartographer.mapping.sparse_pose_graph.proto.ConstraintBuilderOptions)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ConstraintBuilderOptions::CopyFrom(const ConstraintBuilderOptions& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:cartographer.mapping.sparse_pose_graph.proto.ConstraintBuilderOptions)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ConstraintBuilderOptions::IsInitialized() const {
  return true;
}

void ConstraintBuilderOptions::Swap(ConstraintBuilderOptions* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ConstraintBuilderOptions::InternalSwap(ConstraintBuilderOptions* other) {
  std::swap(adaptive_voxel_filter_options_, other->adaptive_voxel_filter_options_);
  std::swap(fast_correlative_scan_matcher_options_, other->fast_correlative_scan_matcher_options_);
  std::swap(fast_correlative_scan_matcher_options_3d_, other->fast_correlative_scan_matcher_options_3d_);
  std::swap(ceres_scan_matcher_options_, other->ceres_scan_matcher_options_);
  std::swap(ceres_scan_matcher_options_3d_, other->ceres_scan_matcher_options_3d_);
  std::swap(high_resolution_adaptive_voxel_filter_options_, other->high_resolution_adaptive_voxel_filter_options_);
  std::swap(low_resolution_adaptive_voxel_filter_options_, other->low_resolution_adaptive_voxel_filter_options_);
  std::swap(sampling_ratio_, other->sampling_ratio_);
  std::swap(max_constraint_distance_, other->max_constraint_distance_);
  std::swap(min_score_, other->min_score_);
  std::swap(global_localization_min_score_, other->global_localization_min_score_);
  std::swap(loop_closure_translation_weight_, other->loop_closure_translation_weight_);
  std::swap(loop_closure_rotation_weight_, other->loop_closure_rotation_weight_);
  std::swap(log_matches_, other->log_matches_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata ConstraintBuilderOptions::GetMetadata() const {
  protobuf_cartographer_2fmapping_2fsparse_5fpose_5fgraph_2fproto_2fconstraint_5fbuilder_5foptions_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_cartographer_2fmapping_2fsparse_5fpose_5fgraph_2fproto_2fconstraint_5fbuilder_5foptions_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// ConstraintBuilderOptions

// optional double sampling_ratio = 1;
bool ConstraintBuilderOptions::has_sampling_ratio() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
void ConstraintBuilderOptions::set_has_sampling_ratio() {
  _has_bits_[0] |= 0x00000080u;
}
void ConstraintBuilderOptions::clear_has_sampling_ratio() {
  _has_bits_[0] &= ~0x00000080u;
}
void ConstraintBuilderOptions::clear_sampling_ratio() {
  sampling_ratio_ = 0;
  clear_has_sampling_ratio();
}
double ConstraintBuilderOptions::sampling_ratio() const {
  // @@protoc_insertion_point(field_get:cartographer.mapping.sparse_pose_graph.proto.ConstraintBuilderOptions.sampling_ratio)
  return sampling_ratio_;
}
void ConstraintBuilderOptions::set_sampling_ratio(double value) {
  set_has_sampling_ratio();
  sampling_ratio_ = value;
  // @@protoc_insertion_point(field_set:cartographer.mapping.sparse_pose_graph.proto.ConstraintBuilderOptions.sampling_ratio)
}

// optional double max_constraint_distance = 2;
bool ConstraintBuilderOptions::has_max_constraint_distance() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
void ConstraintBuilderOptions::set_has_max_constraint_distance() {
  _has_bits_[0] |= 0x00000100u;
}
void ConstraintBuilderOptions::clear_has_max_constraint_distance() {
  _has_bits_[0] &= ~0x00000100u;
}
void ConstraintBuilderOptions::clear_max_constraint_distance() {
  max_constraint_distance_ = 0;
  clear_has_max_constraint_distance();
}
double ConstraintBuilderOptions::max_constraint_distance() const {
  // @@protoc_insertion_point(field_get:cartographer.mapping.sparse_pose_graph.proto.ConstraintBuilderOptions.max_constraint_distance)
  return max_constraint_distance_;
}
void ConstraintBuilderOptions::set_max_constraint_distance(double value) {
  set_has_max_constraint_distance();
  max_constraint_distance_ = value;
  // @@protoc_insertion_point(field_set:cartographer.mapping.sparse_pose_graph.proto.ConstraintBuilderOptions.max_constraint_distance)
}

// optional .cartographer.sensor.proto.AdaptiveVoxelFilterOptions adaptive_voxel_filter_options = 3;
bool ConstraintBuilderOptions::has_adaptive_voxel_filter_options() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void ConstraintBuilderOptions::set_has_adaptive_voxel_filter_options() {
  _has_bits_[0] |= 0x00000001u;
}
void ConstraintBuilderOptions::clear_has_adaptive_voxel_filter_options() {
  _has_bits_[0] &= ~0x00000001u;
}
void ConstraintBuilderOptions::clear_adaptive_voxel_filter_options() {
  if (adaptive_voxel_filter_options_ != NULL) adaptive_voxel_filter_options_->::cartographer::sensor::proto::AdaptiveVoxelFilterOptions::Clear();
  clear_has_adaptive_voxel_filter_options();
}
const ::cartographer::sensor::proto::AdaptiveVoxelFilterOptions& ConstraintBuilderOptions::adaptive_voxel_filter_options() const {
  // @@protoc_insertion_point(field_get:cartographer.mapping.sparse_pose_graph.proto.ConstraintBuilderOptions.adaptive_voxel_filter_options)
  return adaptive_voxel_filter_options_ != NULL ? *adaptive_voxel_filter_options_
                         : *::cartographer::sensor::proto::AdaptiveVoxelFilterOptions::internal_default_instance();
}
::cartographer::sensor::proto::AdaptiveVoxelFilterOptions* ConstraintBuilderOptions::mutable_adaptive_voxel_filter_options() {
  set_has_adaptive_voxel_filter_options();
  if (adaptive_voxel_filter_options_ == NULL) {
    adaptive_voxel_filter_options_ = new ::cartographer::sensor::proto::AdaptiveVoxelFilterOptions;
  }
  // @@protoc_insertion_point(field_mutable:cartographer.mapping.sparse_pose_graph.proto.ConstraintBuilderOptions.adaptive_voxel_filter_options)
  return adaptive_voxel_filter_options_;
}
::cartographer::sensor::proto::AdaptiveVoxelFilterOptions* ConstraintBuilderOptions::release_adaptive_voxel_filter_options() {
  // @@protoc_insertion_point(field_release:cartographer.mapping.sparse_pose_graph.proto.ConstraintBuilderOptions.adaptive_voxel_filter_options)
  clear_has_adaptive_voxel_filter_options();
  ::cartographer::sensor::proto::AdaptiveVoxelFilterOptions* temp = adaptive_voxel_filter_options_;
  adaptive_voxel_filter_options_ = NULL;
  return temp;
}
void ConstraintBuilderOptions::set_allocated_adaptive_voxel_filter_options(::cartographer::sensor::proto::AdaptiveVoxelFilterOptions* adaptive_voxel_filter_options) {
  delete adaptive_voxel_filter_options_;
  adaptive_voxel_filter_options_ = adaptive_voxel_filter_options;
  if (adaptive_voxel_filter_options) {
    set_has_adaptive_voxel_filter_options();
  } else {
    clear_has_adaptive_voxel_filter_options();
  }
  // @@protoc_insertion_point(field_set_allocated:cartographer.mapping.sparse_pose_graph.proto.ConstraintBuilderOptions.adaptive_voxel_filter_options)
}

// optional double min_score = 4;
bool ConstraintBuilderOptions::has_min_score() const {
  return (_has_bits_[0] & 0x00000200u) != 0;
}
void ConstraintBuilderOptions::set_has_min_score() {
  _has_bits_[0] |= 0x00000200u;
}
void ConstraintBuilderOptions::clear_has_min_score() {
  _has_bits_[0] &= ~0x00000200u;
}
void ConstraintBuilderOptions::clear_min_score() {
  min_score_ = 0;
  clear_has_min_score();
}
double ConstraintBuilderOptions::min_score() const {
  // @@protoc_insertion_point(field_get:cartographer.mapping.sparse_pose_graph.proto.ConstraintBuilderOptions.min_score)
  return min_score_;
}
void ConstraintBuilderOptions::set_min_score(double value) {
  set_has_min_score();
  min_score_ = value;
  // @@protoc_insertion_point(field_set:cartographer.mapping.sparse_pose_graph.proto.ConstraintBuilderOptions.min_score)
}

// optional double global_localization_min_score = 5;
bool ConstraintBuilderOptions::has_global_localization_min_score() const {
  return (_has_bits_[0] & 0x00000400u) != 0;
}
void ConstraintBuilderOptions::set_has_global_localization_min_score() {
  _has_bits_[0] |= 0x00000400u;
}
void ConstraintBuilderOptions::clear_has_global_localization_min_score() {
  _has_bits_[0] &= ~0x00000400u;
}
void ConstraintBuilderOptions::clear_global_localization_min_score() {
  global_localization_min_score_ = 0;
  clear_has_global_localization_min_score();
}
double ConstraintBuilderOptions::global_localization_min_score() const {
  // @@protoc_insertion_point(field_get:cartographer.mapping.sparse_pose_graph.proto.ConstraintBuilderOptions.global_localization_min_score)
  return global_localization_min_score_;
}
void ConstraintBuilderOptions::set_global_localization_min_score(double value) {
  set_has_global_localization_min_score();
  global_localization_min_score_ = value;
  // @@protoc_insertion_point(field_set:cartographer.mapping.sparse_pose_graph.proto.ConstraintBuilderOptions.global_localization_min_score)
}

// optional double loop_closure_translation_weight = 13;
bool ConstraintBuilderOptions::has_loop_closure_translation_weight() const {
  return (_has_bits_[0] & 0x00000800u) != 0;
}
void ConstraintBuilderOptions::set_has_loop_closure_translation_weight() {
  _has_bits_[0] |= 0x00000800u;
}
void ConstraintBuilderOptions::clear_has_loop_closure_translation_weight() {
  _has_bits_[0] &= ~0x00000800u;
}
void ConstraintBuilderOptions::clear_loop_closure_translation_weight() {
  loop_closure_translation_weight_ = 0;
  clear_has_loop_closure_translation_weight();
}
double ConstraintBuilderOptions::loop_closure_translation_weight() const {
  // @@protoc_insertion_point(field_get:cartographer.mapping.sparse_pose_graph.proto.ConstraintBuilderOptions.loop_closure_translation_weight)
  return loop_closure_translation_weight_;
}
void ConstraintBuilderOptions::set_loop_closure_translation_weight(double value) {
  set_has_loop_closure_translation_weight();
  loop_closure_translation_weight_ = value;
  // @@protoc_insertion_point(field_set:cartographer.mapping.sparse_pose_graph.proto.ConstraintBuilderOptions.loop_closure_translation_weight)
}

// optional double loop_closure_rotation_weight = 14;
bool ConstraintBuilderOptions::has_loop_closure_rotation_weight() const {
  return (_has_bits_[0] & 0x00001000u) != 0;
}
void ConstraintBuilderOptions::set_has_loop_closure_rotation_weight() {
  _has_bits_[0] |= 0x00001000u;
}
void ConstraintBuilderOptions::clear_has_loop_closure_rotation_weight() {
  _has_bits_[0] &= ~0x00001000u;
}
void ConstraintBuilderOptions::clear_loop_closure_rotation_weight() {
  loop_closure_rotation_weight_ = 0;
  clear_has_loop_closure_rotation_weight();
}
double ConstraintBuilderOptions::loop_closure_rotation_weight() const {
  // @@protoc_insertion_point(field_get:cartographer.mapping.sparse_pose_graph.proto.ConstraintBuilderOptions.loop_closure_rotation_weight)
  return loop_closure_rotation_weight_;
}
void ConstraintBuilderOptions::set_loop_closure_rotation_weight(double value) {
  set_has_loop_closure_rotation_weight();
  loop_closure_rotation_weight_ = value;
  // @@protoc_insertion_point(field_set:cartographer.mapping.sparse_pose_graph.proto.ConstraintBuilderOptions.loop_closure_rotation_weight)
}

// optional bool log_matches = 8;
bool ConstraintBuilderOptions::has_log_matches() const {
  return (_has_bits_[0] & 0x00002000u) != 0;
}
void ConstraintBuilderOptions::set_has_log_matches() {
  _has_bits_[0] |= 0x00002000u;
}
void ConstraintBuilderOptions::clear_has_log_matches() {
  _has_bits_[0] &= ~0x00002000u;
}
void ConstraintBuilderOptions::clear_log_matches() {
  log_matches_ = false;
  clear_has_log_matches();
}
bool ConstraintBuilderOptions::log_matches() const {
  // @@protoc_insertion_point(field_get:cartographer.mapping.sparse_pose_graph.proto.ConstraintBuilderOptions.log_matches)
  return log_matches_;
}
void ConstraintBuilderOptions::set_log_matches(bool value) {
  set_has_log_matches();
  log_matches_ = value;
  // @@protoc_insertion_point(field_set:cartographer.mapping.sparse_pose_graph.proto.ConstraintBuilderOptions.log_matches)
}

// optional .cartographer.mapping_2d.scan_matching.proto.FastCorrelativeScanMatcherOptions fast_correlative_scan_matcher_options = 9;
bool ConstraintBuilderOptions::has_fast_correlative_scan_matcher_options() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
void ConstraintBuilderOptions::set_has_fast_correlative_scan_matcher_options() {
  _has_bits_[0] |= 0x00000002u;
}
void ConstraintBuilderOptions::clear_has_fast_correlative_scan_matcher_options() {
  _has_bits_[0] &= ~0x00000002u;
}
void ConstraintBuilderOptions::clear_fast_correlative_scan_matcher_options() {
  if (fast_correlative_scan_matcher_options_ != NULL) fast_correlative_scan_matcher_options_->::cartographer::mapping_2d::scan_matching::proto::FastCorrelativeScanMatcherOptions::Clear();
  clear_has_fast_correlative_scan_matcher_options();
}
const ::cartographer::mapping_2d::scan_matching::proto::FastCorrelativeScanMatcherOptions& ConstraintBuilderOptions::fast_correlative_scan_matcher_options() const {
  // @@protoc_insertion_point(field_get:cartographer.mapping.sparse_pose_graph.proto.ConstraintBuilderOptions.fast_correlative_scan_matcher_options)
  return fast_correlative_scan_matcher_options_ != NULL ? *fast_correlative_scan_matcher_options_
                         : *::cartographer::mapping_2d::scan_matching::proto::FastCorrelativeScanMatcherOptions::internal_default_instance();
}
::cartographer::mapping_2d::scan_matching::proto::FastCorrelativeScanMatcherOptions* ConstraintBuilderOptions::mutable_fast_correlative_scan_matcher_options() {
  set_has_fast_correlative_scan_matcher_options();
  if (fast_correlative_scan_matcher_options_ == NULL) {
    fast_correlative_scan_matcher_options_ = new ::cartographer::mapping_2d::scan_matching::proto::FastCorrelativeScanMatcherOptions;
  }
  // @@protoc_insertion_point(field_mutable:cartographer.mapping.sparse_pose_graph.proto.ConstraintBuilderOptions.fast_correlative_scan_matcher_options)
  return fast_correlative_scan_matcher_options_;
}
::cartographer::mapping_2d::scan_matching::proto::FastCorrelativeScanMatcherOptions* ConstraintBuilderOptions::release_fast_correlative_scan_matcher_options() {
  // @@protoc_insertion_point(field_release:cartographer.mapping.sparse_pose_graph.proto.ConstraintBuilderOptions.fast_correlative_scan_matcher_options)
  clear_has_fast_correlative_scan_matcher_options();
  ::cartographer::mapping_2d::scan_matching::proto::FastCorrelativeScanMatcherOptions* temp = fast_correlative_scan_matcher_options_;
  fast_correlative_scan_matcher_options_ = NULL;
  return temp;
}
void ConstraintBuilderOptions::set_allocated_fast_correlative_scan_matcher_options(::cartographer::mapping_2d::scan_matching::proto::FastCorrelativeScanMatcherOptions* fast_correlative_scan_matcher_options) {
  delete fast_correlative_scan_matcher_options_;
  fast_correlative_scan_matcher_options_ = fast_correlative_scan_matcher_options;
  if (fast_correlative_scan_matcher_options) {
    set_has_fast_correlative_scan_matcher_options();
  } else {
    clear_has_fast_correlative_scan_matcher_options();
  }
  // @@protoc_insertion_point(field_set_allocated:cartographer.mapping.sparse_pose_graph.proto.ConstraintBuilderOptions.fast_correlative_scan_matcher_options)
}

// optional .cartographer.mapping_2d.scan_matching.proto.CeresScanMatcherOptions ceres_scan_matcher_options = 11;
bool ConstraintBuilderOptions::has_ceres_scan_matcher_options() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
void ConstraintBuilderOptions::set_has_ceres_scan_matcher_options() {
  _has_bits_[0] |= 0x00000008u;
}
void ConstraintBuilderOptions::clear_has_ceres_scan_matcher_options() {
  _has_bits_[0] &= ~0x00000008u;
}
void ConstraintBuilderOptions::clear_ceres_scan_matcher_options() {
  if (ceres_scan_matcher_options_ != NULL) ceres_scan_matcher_options_->::cartographer::mapping_2d::scan_matching::proto::CeresScanMatcherOptions::Clear();
  clear_has_ceres_scan_matcher_options();
}
const ::cartographer::mapping_2d::scan_matching::proto::CeresScanMatcherOptions& ConstraintBuilderOptions::ceres_scan_matcher_options() const {
  // @@protoc_insertion_point(field_get:cartographer.mapping.sparse_pose_graph.proto.ConstraintBuilderOptions.ceres_scan_matcher_options)
  return ceres_scan_matcher_options_ != NULL ? *ceres_scan_matcher_options_
                         : *::cartographer::mapping_2d::scan_matching::proto::CeresScanMatcherOptions::internal_default_instance();
}
::cartographer::mapping_2d::scan_matching::proto::CeresScanMatcherOptions* ConstraintBuilderOptions::mutable_ceres_scan_matcher_options() {
  set_has_ceres_scan_matcher_options();
  if (ceres_scan_matcher_options_ == NULL) {
    ceres_scan_matcher_options_ = new ::cartographer::mapping_2d::scan_matching::proto::CeresScanMatcherOptions;
  }
  // @@protoc_insertion_point(field_mutable:cartographer.mapping.sparse_pose_graph.proto.ConstraintBuilderOptions.ceres_scan_matcher_options)
  return ceres_scan_matcher_options_;
}
::cartographer::mapping_2d::scan_matching::proto::CeresScanMatcherOptions* ConstraintBuilderOptions::release_ceres_scan_matcher_options() {
  // @@protoc_insertion_point(field_release:cartographer.mapping.sparse_pose_graph.proto.ConstraintBuilderOptions.ceres_scan_matcher_options)
  clear_has_ceres_scan_matcher_options();
  ::cartographer::mapping_2d::scan_matching::proto::CeresScanMatcherOptions* temp = ceres_scan_matcher_options_;
  ceres_scan_matcher_options_ = NULL;
  return temp;
}
void ConstraintBuilderOptions::set_allocated_ceres_scan_matcher_options(::cartographer::mapping_2d::scan_matching::proto::CeresScanMatcherOptions* ceres_scan_matcher_options) {
  delete ceres_scan_matcher_options_;
  ceres_scan_matcher_options_ = ceres_scan_matcher_options;
  if (ceres_scan_matcher_options) {
    set_has_ceres_scan_matcher_options();
  } else {
    clear_has_ceres_scan_matcher_options();
  }
  // @@protoc_insertion_point(field_set_allocated:cartographer.mapping.sparse_pose_graph.proto.ConstraintBuilderOptions.ceres_scan_matcher_options)
}

// optional .cartographer.mapping_3d.scan_matching.proto.FastCorrelativeScanMatcherOptions fast_correlative_scan_matcher_options_3d = 10;
bool ConstraintBuilderOptions::has_fast_correlative_scan_matcher_options_3d() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
void ConstraintBuilderOptions::set_has_fast_correlative_scan_matcher_options_3d() {
  _has_bits_[0] |= 0x00000004u;
}
void ConstraintBuilderOptions::clear_has_fast_correlative_scan_matcher_options_3d() {
  _has_bits_[0] &= ~0x00000004u;
}
void ConstraintBuilderOptions::clear_fast_correlative_scan_matcher_options_3d() {
  if (fast_correlative_scan_matcher_options_3d_ != NULL) fast_correlative_scan_matcher_options_3d_->::cartographer::mapping_3d::scan_matching::proto::FastCorrelativeScanMatcherOptions::Clear();
  clear_has_fast_correlative_scan_matcher_options_3d();
}
const ::cartographer::mapping_3d::scan_matching::proto::FastCorrelativeScanMatcherOptions& ConstraintBuilderOptions::fast_correlative_scan_matcher_options_3d() const {
  // @@protoc_insertion_point(field_get:cartographer.mapping.sparse_pose_graph.proto.ConstraintBuilderOptions.fast_correlative_scan_matcher_options_3d)
  return fast_correlative_scan_matcher_options_3d_ != NULL ? *fast_correlative_scan_matcher_options_3d_
                         : *::cartographer::mapping_3d::scan_matching::proto::FastCorrelativeScanMatcherOptions::internal_default_instance();
}
::cartographer::mapping_3d::scan_matching::proto::FastCorrelativeScanMatcherOptions* ConstraintBuilderOptions::mutable_fast_correlative_scan_matcher_options_3d() {
  set_has_fast_correlative_scan_matcher_options_3d();
  if (fast_correlative_scan_matcher_options_3d_ == NULL) {
    fast_correlative_scan_matcher_options_3d_ = new ::cartographer::mapping_3d::scan_matching::proto::FastCorrelativeScanMatcherOptions;
  }
  // @@protoc_insertion_point(field_mutable:cartographer.mapping.sparse_pose_graph.proto.ConstraintBuilderOptions.fast_correlative_scan_matcher_options_3d)
  return fast_correlative_scan_matcher_options_3d_;
}
::cartographer::mapping_3d::scan_matching::proto::FastCorrelativeScanMatcherOptions* ConstraintBuilderOptions::release_fast_correlative_scan_matcher_options_3d() {
  // @@protoc_insertion_point(field_release:cartographer.mapping.sparse_pose_graph.proto.ConstraintBuilderOptions.fast_correlative_scan_matcher_options_3d)
  clear_has_fast_correlative_scan_matcher_options_3d();
  ::cartographer::mapping_3d::scan_matching::proto::FastCorrelativeScanMatcherOptions* temp = fast_correlative_scan_matcher_options_3d_;
  fast_correlative_scan_matcher_options_3d_ = NULL;
  return temp;
}
void ConstraintBuilderOptions::set_allocated_fast_correlative_scan_matcher_options_3d(::cartographer::mapping_3d::scan_matching::proto::FastCorrelativeScanMatcherOptions* fast_correlative_scan_matcher_options_3d) {
  delete fast_correlative_scan_matcher_options_3d_;
  fast_correlative_scan_matcher_options_3d_ = fast_correlative_scan_matcher_options_3d;
  if (fast_correlative_scan_matcher_options_3d) {
    set_has_fast_correlative_scan_matcher_options_3d();
  } else {
    clear_has_fast_correlative_scan_matcher_options_3d();
  }
  // @@protoc_insertion_point(field_set_allocated:cartographer.mapping.sparse_pose_graph.proto.ConstraintBuilderOptions.fast_correlative_scan_matcher_options_3d)
}

// optional .cartographer.sensor.proto.AdaptiveVoxelFilterOptions high_resolution_adaptive_voxel_filter_options = 15;
bool ConstraintBuilderOptions::has_high_resolution_adaptive_voxel_filter_options() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
void ConstraintBuilderOptions::set_has_high_resolution_adaptive_voxel_filter_options() {
  _has_bits_[0] |= 0x00000020u;
}
void ConstraintBuilderOptions::clear_has_high_resolution_adaptive_voxel_filter_options() {
  _has_bits_[0] &= ~0x00000020u;
}
void ConstraintBuilderOptions::clear_high_resolution_adaptive_voxel_filter_options() {
  if (high_resolution_adaptive_voxel_filter_options_ != NULL) high_resolution_adaptive_voxel_filter_options_->::cartographer::sensor::proto::AdaptiveVoxelFilterOptions::Clear();
  clear_has_high_resolution_adaptive_voxel_filter_options();
}
const ::cartographer::sensor::proto::AdaptiveVoxelFilterOptions& ConstraintBuilderOptions::high_resolution_adaptive_voxel_filter_options() const {
  // @@protoc_insertion_point(field_get:cartographer.mapping.sparse_pose_graph.proto.ConstraintBuilderOptions.high_resolution_adaptive_voxel_filter_options)
  return high_resolution_adaptive_voxel_filter_options_ != NULL ? *high_resolution_adaptive_voxel_filter_options_
                         : *::cartographer::sensor::proto::AdaptiveVoxelFilterOptions::internal_default_instance();
}
::cartographer::sensor::proto::AdaptiveVoxelFilterOptions* ConstraintBuilderOptions::mutable_high_resolution_adaptive_voxel_filter_options() {
  set_has_high_resolution_adaptive_voxel_filter_options();
  if (high_resolution_adaptive_voxel_filter_options_ == NULL) {
    high_resolution_adaptive_voxel_filter_options_ = new ::cartographer::sensor::proto::AdaptiveVoxelFilterOptions;
  }
  // @@protoc_insertion_point(field_mutable:cartographer.mapping.sparse_pose_graph.proto.ConstraintBuilderOptions.high_resolution_adaptive_voxel_filter_options)
  return high_resolution_adaptive_voxel_filter_options_;
}
::cartographer::sensor::proto::AdaptiveVoxelFilterOptions* ConstraintBuilderOptions::release_high_resolution_adaptive_voxel_filter_options() {
  // @@protoc_insertion_point(field_release:cartographer.mapping.sparse_pose_graph.proto.ConstraintBuilderOptions.high_resolution_adaptive_voxel_filter_options)
  clear_has_high_resolution_adaptive_voxel_filter_options();
  ::cartographer::sensor::proto::AdaptiveVoxelFilterOptions* temp = high_resolution_adaptive_voxel_filter_options_;
  high_resolution_adaptive_voxel_filter_options_ = NULL;
  return temp;
}
void ConstraintBuilderOptions::set_allocated_high_resolution_adaptive_voxel_filter_options(::cartographer::sensor::proto::AdaptiveVoxelFilterOptions* high_resolution_adaptive_voxel_filter_options) {
  delete high_resolution_adaptive_voxel_filter_options_;
  high_resolution_adaptive_voxel_filter_options_ = high_resolution_adaptive_voxel_filter_options;
  if (high_resolution_adaptive_voxel_filter_options) {
    set_has_high_resolution_adaptive_voxel_filter_options();
  } else {
    clear_has_high_resolution_adaptive_voxel_filter_options();
  }
  // @@protoc_insertion_point(field_set_allocated:cartographer.mapping.sparse_pose_graph.proto.ConstraintBuilderOptions.high_resolution_adaptive_voxel_filter_options)
}

// optional .cartographer.sensor.proto.AdaptiveVoxelFilterOptions low_resolution_adaptive_voxel_filter_options = 16;
bool ConstraintBuilderOptions::has_low_resolution_adaptive_voxel_filter_options() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
void ConstraintBuilderOptions::set_has_low_resolution_adaptive_voxel_filter_options() {
  _has_bits_[0] |= 0x00000040u;
}
void ConstraintBuilderOptions::clear_has_low_resolution_adaptive_voxel_filter_options() {
  _has_bits_[0] &= ~0x00000040u;
}
void ConstraintBuilderOptions::clear_low_resolution_adaptive_voxel_filter_options() {
  if (low_resolution_adaptive_voxel_filter_options_ != NULL) low_resolution_adaptive_voxel_filter_options_->::cartographer::sensor::proto::AdaptiveVoxelFilterOptions::Clear();
  clear_has_low_resolution_adaptive_voxel_filter_options();
}
const ::cartographer::sensor::proto::AdaptiveVoxelFilterOptions& ConstraintBuilderOptions::low_resolution_adaptive_voxel_filter_options() const {
  // @@protoc_insertion_point(field_get:cartographer.mapping.sparse_pose_graph.proto.ConstraintBuilderOptions.low_resolution_adaptive_voxel_filter_options)
  return low_resolution_adaptive_voxel_filter_options_ != NULL ? *low_resolution_adaptive_voxel_filter_options_
                         : *::cartographer::sensor::proto::AdaptiveVoxelFilterOptions::internal_default_instance();
}
::cartographer::sensor::proto::AdaptiveVoxelFilterOptions* ConstraintBuilderOptions::mutable_low_resolution_adaptive_voxel_filter_options() {
  set_has_low_resolution_adaptive_voxel_filter_options();
  if (low_resolution_adaptive_voxel_filter_options_ == NULL) {
    low_resolution_adaptive_voxel_filter_options_ = new ::cartographer::sensor::proto::AdaptiveVoxelFilterOptions;
  }
  // @@protoc_insertion_point(field_mutable:cartographer.mapping.sparse_pose_graph.proto.ConstraintBuilderOptions.low_resolution_adaptive_voxel_filter_options)
  return low_resolution_adaptive_voxel_filter_options_;
}
::cartographer::sensor::proto::AdaptiveVoxelFilterOptions* ConstraintBuilderOptions::release_low_resolution_adaptive_voxel_filter_options() {
  // @@protoc_insertion_point(field_release:cartographer.mapping.sparse_pose_graph.proto.ConstraintBuilderOptions.low_resolution_adaptive_voxel_filter_options)
  clear_has_low_resolution_adaptive_voxel_filter_options();
  ::cartographer::sensor::proto::AdaptiveVoxelFilterOptions* temp = low_resolution_adaptive_voxel_filter_options_;
  low_resolution_adaptive_voxel_filter_options_ = NULL;
  return temp;
}
void ConstraintBuilderOptions::set_allocated_low_resolution_adaptive_voxel_filter_options(::cartographer::sensor::proto::AdaptiveVoxelFilterOptions* low_resolution_adaptive_voxel_filter_options) {
  delete low_resolution_adaptive_voxel_filter_options_;
  low_resolution_adaptive_voxel_filter_options_ = low_resolution_adaptive_voxel_filter_options;
  if (low_resolution_adaptive_voxel_filter_options) {
    set_has_low_resolution_adaptive_voxel_filter_options();
  } else {
    clear_has_low_resolution_adaptive_voxel_filter_options();
  }
  // @@protoc_insertion_point(field_set_allocated:cartographer.mapping.sparse_pose_graph.proto.ConstraintBuilderOptions.low_resolution_adaptive_voxel_filter_options)
}

// optional .cartographer.mapping_3d.scan_matching.proto.CeresScanMatcherOptions ceres_scan_matcher_options_3d = 12;
bool ConstraintBuilderOptions::has_ceres_scan_matcher_options_3d() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
void ConstraintBuilderOptions::set_has_ceres_scan_matcher_options_3d() {
  _has_bits_[0] |= 0x00000010u;
}
void ConstraintBuilderOptions::clear_has_ceres_scan_matcher_options_3d() {
  _has_bits_[0] &= ~0x00000010u;
}
void ConstraintBuilderOptions::clear_ceres_scan_matcher_options_3d() {
  if (ceres_scan_matcher_options_3d_ != NULL) ceres_scan_matcher_options_3d_->::cartographer::mapping_3d::scan_matching::proto::CeresScanMatcherOptions::Clear();
  clear_has_ceres_scan_matcher_options_3d();
}
const ::cartographer::mapping_3d::scan_matching::proto::CeresScanMatcherOptions& ConstraintBuilderOptions::ceres_scan_matcher_options_3d() const {
  // @@protoc_insertion_point(field_get:cartographer.mapping.sparse_pose_graph.proto.ConstraintBuilderOptions.ceres_scan_matcher_options_3d)
  return ceres_scan_matcher_options_3d_ != NULL ? *ceres_scan_matcher_options_3d_
                         : *::cartographer::mapping_3d::scan_matching::proto::CeresScanMatcherOptions::internal_default_instance();
}
::cartographer::mapping_3d::scan_matching::proto::CeresScanMatcherOptions* ConstraintBuilderOptions::mutable_ceres_scan_matcher_options_3d() {
  set_has_ceres_scan_matcher_options_3d();
  if (ceres_scan_matcher_options_3d_ == NULL) {
    ceres_scan_matcher_options_3d_ = new ::cartographer::mapping_3d::scan_matching::proto::CeresScanMatcherOptions;
  }
  // @@protoc_insertion_point(field_mutable:cartographer.mapping.sparse_pose_graph.proto.ConstraintBuilderOptions.ceres_scan_matcher_options_3d)
  return ceres_scan_matcher_options_3d_;
}
::cartographer::mapping_3d::scan_matching::proto::CeresScanMatcherOptions* ConstraintBuilderOptions::release_ceres_scan_matcher_options_3d() {
  // @@protoc_insertion_point(field_release:cartographer.mapping.sparse_pose_graph.proto.ConstraintBuilderOptions.ceres_scan_matcher_options_3d)
  clear_has_ceres_scan_matcher_options_3d();
  ::cartographer::mapping_3d::scan_matching::proto::CeresScanMatcherOptions* temp = ceres_scan_matcher_options_3d_;
  ceres_scan_matcher_options_3d_ = NULL;
  return temp;
}
void ConstraintBuilderOptions::set_allocated_ceres_scan_matcher_options_3d(::cartographer::mapping_3d::scan_matching::proto::CeresScanMatcherOptions* ceres_scan_matcher_options_3d) {
  delete ceres_scan_matcher_options_3d_;
  ceres_scan_matcher_options_3d_ = ceres_scan_matcher_options_3d;
  if (ceres_scan_matcher_options_3d) {
    set_has_ceres_scan_matcher_options_3d();
  } else {
    clear_has_ceres_scan_matcher_options_3d();
  }
  // @@protoc_insertion_point(field_set_allocated:cartographer.mapping.sparse_pose_graph.proto.ConstraintBuilderOptions.ceres_scan_matcher_options_3d)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace proto
}  // namespace sparse_pose_graph
}  // namespace mapping
}  // namespace cartographer

// @@protoc_insertion_point(global_scope)
