// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cartographer/mapping/sparse_pose_graph/proto/optimization_problem_options.proto

#ifndef PROTOBUF_cartographer_2fmapping_2fsparse_5fpose_5fgraph_2fproto_2foptimization_5fproblem_5foptions_2eproto__INCLUDED
#define PROTOBUF_cartographer_2fmapping_2fsparse_5fpose_5fgraph_2fproto_2foptimization_5fproblem_5foptions_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3003000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3003000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "cartographer/common/proto/ceres_solver_options.pb.h"
// @@protoc_insertion_point(includes)
namespace cartographer {
namespace mapping {
namespace sparse_pose_graph {
namespace proto {
class OptimizationProblemOptions;
class OptimizationProblemOptionsDefaultTypeInternal;
extern OptimizationProblemOptionsDefaultTypeInternal _OptimizationProblemOptions_default_instance_;
}  // namespace proto
}  // namespace sparse_pose_graph
}  // namespace mapping
}  // namespace cartographer

namespace cartographer {
namespace mapping {
namespace sparse_pose_graph {
namespace proto {

namespace protobuf_cartographer_2fmapping_2fsparse_5fpose_5fgraph_2fproto_2foptimization_5fproblem_5foptions_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_cartographer_2fmapping_2fsparse_5fpose_5fgraph_2fproto_2foptimization_5fproblem_5foptions_2eproto

// ===================================================================

class OptimizationProblemOptions : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:cartographer.mapping.sparse_pose_graph.proto.OptimizationProblemOptions) */ {
 public:
  OptimizationProblemOptions();
  virtual ~OptimizationProblemOptions();

  OptimizationProblemOptions(const OptimizationProblemOptions& from);

  inline OptimizationProblemOptions& operator=(const OptimizationProblemOptions& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const OptimizationProblemOptions& default_instance();

  static inline const OptimizationProblemOptions* internal_default_instance() {
    return reinterpret_cast<const OptimizationProblemOptions*>(
               &_OptimizationProblemOptions_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(OptimizationProblemOptions* other);

  // implements Message ----------------------------------------------

  inline OptimizationProblemOptions* New() const PROTOBUF_FINAL { return New(NULL); }

  OptimizationProblemOptions* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const OptimizationProblemOptions& from);
  void MergeFrom(const OptimizationProblemOptions& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(OptimizationProblemOptions* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .cartographer.common.proto.CeresSolverOptions ceres_solver_options = 7;
  bool has_ceres_solver_options() const;
  void clear_ceres_solver_options();
  static const int kCeresSolverOptionsFieldNumber = 7;
  const ::cartographer::common::proto::CeresSolverOptions& ceres_solver_options() const;
  ::cartographer::common::proto::CeresSolverOptions* mutable_ceres_solver_options();
  ::cartographer::common::proto::CeresSolverOptions* release_ceres_solver_options();
  void set_allocated_ceres_solver_options(::cartographer::common::proto::CeresSolverOptions* ceres_solver_options);

  // optional double huber_scale = 1;
  bool has_huber_scale() const;
  void clear_huber_scale();
  static const int kHuberScaleFieldNumber = 1;
  double huber_scale() const;
  void set_huber_scale(double value);

  // optional double consecutive_scan_translation_penalty_factor = 2;
  bool has_consecutive_scan_translation_penalty_factor() const;
  void clear_consecutive_scan_translation_penalty_factor();
  static const int kConsecutiveScanTranslationPenaltyFactorFieldNumber = 2;
  double consecutive_scan_translation_penalty_factor() const;
  void set_consecutive_scan_translation_penalty_factor(double value);

  // optional double consecutive_scan_rotation_penalty_factor = 3;
  bool has_consecutive_scan_rotation_penalty_factor() const;
  void clear_consecutive_scan_rotation_penalty_factor();
  static const int kConsecutiveScanRotationPenaltyFactorFieldNumber = 3;
  double consecutive_scan_rotation_penalty_factor() const;
  void set_consecutive_scan_rotation_penalty_factor(double value);

  // optional double acceleration_weight = 8;
  bool has_acceleration_weight() const;
  void clear_acceleration_weight();
  static const int kAccelerationWeightFieldNumber = 8;
  double acceleration_weight() const;
  void set_acceleration_weight(double value);

  // optional bool log_solver_summary = 5;
  bool has_log_solver_summary() const;
  void clear_log_solver_summary();
  static const int kLogSolverSummaryFieldNumber = 5;
  bool log_solver_summary() const;
  void set_log_solver_summary(bool value);

  // optional double rotation_weight = 9;
  bool has_rotation_weight() const;
  void clear_rotation_weight();
  static const int kRotationWeightFieldNumber = 9;
  double rotation_weight() const;
  void set_rotation_weight(double value);

  // @@protoc_insertion_point(class_scope:cartographer.mapping.sparse_pose_graph.proto.OptimizationProblemOptions)
 private:
  void set_has_huber_scale();
  void clear_has_huber_scale();
  void set_has_acceleration_weight();
  void clear_has_acceleration_weight();
  void set_has_rotation_weight();
  void clear_has_rotation_weight();
  void set_has_consecutive_scan_translation_penalty_factor();
  void clear_has_consecutive_scan_translation_penalty_factor();
  void set_has_consecutive_scan_rotation_penalty_factor();
  void clear_has_consecutive_scan_rotation_penalty_factor();
  void set_has_log_solver_summary();
  void clear_has_log_solver_summary();
  void set_has_ceres_solver_options();
  void clear_has_ceres_solver_options();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::cartographer::common::proto::CeresSolverOptions* ceres_solver_options_;
  double huber_scale_;
  double consecutive_scan_translation_penalty_factor_;
  double consecutive_scan_rotation_penalty_factor_;
  double acceleration_weight_;
  bool log_solver_summary_;
  double rotation_weight_;
  friend struct protobuf_cartographer_2fmapping_2fsparse_5fpose_5fgraph_2fproto_2foptimization_5fproblem_5foptions_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// OptimizationProblemOptions

// optional double huber_scale = 1;
inline bool OptimizationProblemOptions::has_huber_scale() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void OptimizationProblemOptions::set_has_huber_scale() {
  _has_bits_[0] |= 0x00000002u;
}
inline void OptimizationProblemOptions::clear_has_huber_scale() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void OptimizationProblemOptions::clear_huber_scale() {
  huber_scale_ = 0;
  clear_has_huber_scale();
}
inline double OptimizationProblemOptions::huber_scale() const {
  // @@protoc_insertion_point(field_get:cartographer.mapping.sparse_pose_graph.proto.OptimizationProblemOptions.huber_scale)
  return huber_scale_;
}
inline void OptimizationProblemOptions::set_huber_scale(double value) {
  set_has_huber_scale();
  huber_scale_ = value;
  // @@protoc_insertion_point(field_set:cartographer.mapping.sparse_pose_graph.proto.OptimizationProblemOptions.huber_scale)
}

// optional double acceleration_weight = 8;
inline bool OptimizationProblemOptions::has_acceleration_weight() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void OptimizationProblemOptions::set_has_acceleration_weight() {
  _has_bits_[0] |= 0x00000010u;
}
inline void OptimizationProblemOptions::clear_has_acceleration_weight() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void OptimizationProblemOptions::clear_acceleration_weight() {
  acceleration_weight_ = 0;
  clear_has_acceleration_weight();
}
inline double OptimizationProblemOptions::acceleration_weight() const {
  // @@protoc_insertion_point(field_get:cartographer.mapping.sparse_pose_graph.proto.OptimizationProblemOptions.acceleration_weight)
  return acceleration_weight_;
}
inline void OptimizationProblemOptions::set_acceleration_weight(double value) {
  set_has_acceleration_weight();
  acceleration_weight_ = value;
  // @@protoc_insertion_point(field_set:cartographer.mapping.sparse_pose_graph.proto.OptimizationProblemOptions.acceleration_weight)
}

// optional double rotation_weight = 9;
inline bool OptimizationProblemOptions::has_rotation_weight() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void OptimizationProblemOptions::set_has_rotation_weight() {
  _has_bits_[0] |= 0x00000040u;
}
inline void OptimizationProblemOptions::clear_has_rotation_weight() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void OptimizationProblemOptions::clear_rotation_weight() {
  rotation_weight_ = 0;
  clear_has_rotation_weight();
}
inline double OptimizationProblemOptions::rotation_weight() const {
  // @@protoc_insertion_point(field_get:cartographer.mapping.sparse_pose_graph.proto.OptimizationProblemOptions.rotation_weight)
  return rotation_weight_;
}
inline void OptimizationProblemOptions::set_rotation_weight(double value) {
  set_has_rotation_weight();
  rotation_weight_ = value;
  // @@protoc_insertion_point(field_set:cartographer.mapping.sparse_pose_graph.proto.OptimizationProblemOptions.rotation_weight)
}

// optional double consecutive_scan_translation_penalty_factor = 2;
inline bool OptimizationProblemOptions::has_consecutive_scan_translation_penalty_factor() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void OptimizationProblemOptions::set_has_consecutive_scan_translation_penalty_factor() {
  _has_bits_[0] |= 0x00000004u;
}
inline void OptimizationProblemOptions::clear_has_consecutive_scan_translation_penalty_factor() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void OptimizationProblemOptions::clear_consecutive_scan_translation_penalty_factor() {
  consecutive_scan_translation_penalty_factor_ = 0;
  clear_has_consecutive_scan_translation_penalty_factor();
}
inline double OptimizationProblemOptions::consecutive_scan_translation_penalty_factor() const {
  // @@protoc_insertion_point(field_get:cartographer.mapping.sparse_pose_graph.proto.OptimizationProblemOptions.consecutive_scan_translation_penalty_factor)
  return consecutive_scan_translation_penalty_factor_;
}
inline void OptimizationProblemOptions::set_consecutive_scan_translation_penalty_factor(double value) {
  set_has_consecutive_scan_translation_penalty_factor();
  consecutive_scan_translation_penalty_factor_ = value;
  // @@protoc_insertion_point(field_set:cartographer.mapping.sparse_pose_graph.proto.OptimizationProblemOptions.consecutive_scan_translation_penalty_factor)
}

// optional double consecutive_scan_rotation_penalty_factor = 3;
inline bool OptimizationProblemOptions::has_consecutive_scan_rotation_penalty_factor() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void OptimizationProblemOptions::set_has_consecutive_scan_rotation_penalty_factor() {
  _has_bits_[0] |= 0x00000008u;
}
inline void OptimizationProblemOptions::clear_has_consecutive_scan_rotation_penalty_factor() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void OptimizationProblemOptions::clear_consecutive_scan_rotation_penalty_factor() {
  consecutive_scan_rotation_penalty_factor_ = 0;
  clear_has_consecutive_scan_rotation_penalty_factor();
}
inline double OptimizationProblemOptions::consecutive_scan_rotation_penalty_factor() const {
  // @@protoc_insertion_point(field_get:cartographer.mapping.sparse_pose_graph.proto.OptimizationProblemOptions.consecutive_scan_rotation_penalty_factor)
  return consecutive_scan_rotation_penalty_factor_;
}
inline void OptimizationProblemOptions::set_consecutive_scan_rotation_penalty_factor(double value) {
  set_has_consecutive_scan_rotation_penalty_factor();
  consecutive_scan_rotation_penalty_factor_ = value;
  // @@protoc_insertion_point(field_set:cartographer.mapping.sparse_pose_graph.proto.OptimizationProblemOptions.consecutive_scan_rotation_penalty_factor)
}

// optional bool log_solver_summary = 5;
inline bool OptimizationProblemOptions::has_log_solver_summary() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void OptimizationProblemOptions::set_has_log_solver_summary() {
  _has_bits_[0] |= 0x00000020u;
}
inline void OptimizationProblemOptions::clear_has_log_solver_summary() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void OptimizationProblemOptions::clear_log_solver_summary() {
  log_solver_summary_ = false;
  clear_has_log_solver_summary();
}
inline bool OptimizationProblemOptions::log_solver_summary() const {
  // @@protoc_insertion_point(field_get:cartographer.mapping.sparse_pose_graph.proto.OptimizationProblemOptions.log_solver_summary)
  return log_solver_summary_;
}
inline void OptimizationProblemOptions::set_log_solver_summary(bool value) {
  set_has_log_solver_summary();
  log_solver_summary_ = value;
  // @@protoc_insertion_point(field_set:cartographer.mapping.sparse_pose_graph.proto.OptimizationProblemOptions.log_solver_summary)
}

// optional .cartographer.common.proto.CeresSolverOptions ceres_solver_options = 7;
inline bool OptimizationProblemOptions::has_ceres_solver_options() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void OptimizationProblemOptions::set_has_ceres_solver_options() {
  _has_bits_[0] |= 0x00000001u;
}
inline void OptimizationProblemOptions::clear_has_ceres_solver_options() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void OptimizationProblemOptions::clear_ceres_solver_options() {
  if (ceres_solver_options_ != NULL) ceres_solver_options_->::cartographer::common::proto::CeresSolverOptions::Clear();
  clear_has_ceres_solver_options();
}
inline const ::cartographer::common::proto::CeresSolverOptions& OptimizationProblemOptions::ceres_solver_options() const {
  // @@protoc_insertion_point(field_get:cartographer.mapping.sparse_pose_graph.proto.OptimizationProblemOptions.ceres_solver_options)
  return ceres_solver_options_ != NULL ? *ceres_solver_options_
                         : *::cartographer::common::proto::CeresSolverOptions::internal_default_instance();
}
inline ::cartographer::common::proto::CeresSolverOptions* OptimizationProblemOptions::mutable_ceres_solver_options() {
  set_has_ceres_solver_options();
  if (ceres_solver_options_ == NULL) {
    ceres_solver_options_ = new ::cartographer::common::proto::CeresSolverOptions;
  }
  // @@protoc_insertion_point(field_mutable:cartographer.mapping.sparse_pose_graph.proto.OptimizationProblemOptions.ceres_solver_options)
  return ceres_solver_options_;
}
inline ::cartographer::common::proto::CeresSolverOptions* OptimizationProblemOptions::release_ceres_solver_options() {
  // @@protoc_insertion_point(field_release:cartographer.mapping.sparse_pose_graph.proto.OptimizationProblemOptions.ceres_solver_options)
  clear_has_ceres_solver_options();
  ::cartographer::common::proto::CeresSolverOptions* temp = ceres_solver_options_;
  ceres_solver_options_ = NULL;
  return temp;
}
inline void OptimizationProblemOptions::set_allocated_ceres_solver_options(::cartographer::common::proto::CeresSolverOptions* ceres_solver_options) {
  delete ceres_solver_options_;
  ceres_solver_options_ = ceres_solver_options;
  if (ceres_solver_options) {
    set_has_ceres_solver_options();
  } else {
    clear_has_ceres_solver_options();
  }
  // @@protoc_insertion_point(field_set_allocated:cartographer.mapping.sparse_pose_graph.proto.OptimizationProblemOptions.ceres_solver_options)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)


}  // namespace proto
}  // namespace sparse_pose_graph
}  // namespace mapping
}  // namespace cartographer

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_cartographer_2fmapping_2fsparse_5fpose_5fgraph_2fproto_2foptimization_5fproblem_5foptions_2eproto__INCLUDED
