// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cartographer/mapping_2d/proto/map_limits.proto

#ifndef PROTOBUF_cartographer_2fmapping_5f2d_2fproto_2fmap_5flimits_2eproto__INCLUDED
#define PROTOBUF_cartographer_2fmapping_5f2d_2fproto_2fmap_5flimits_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3003000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3003000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "cartographer/mapping_2d/proto/cell_limits.pb.h"
#include "cartographer/transform/proto/transform.pb.h"
// @@protoc_insertion_point(includes)
namespace cartographer {
namespace mapping_2d {
namespace proto {
class MapLimits;
class MapLimitsDefaultTypeInternal;
extern MapLimitsDefaultTypeInternal _MapLimits_default_instance_;
}  // namespace proto
}  // namespace mapping_2d
}  // namespace cartographer

namespace cartographer {
namespace mapping_2d {
namespace proto {

namespace protobuf_cartographer_2fmapping_5f2d_2fproto_2fmap_5flimits_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_cartographer_2fmapping_5f2d_2fproto_2fmap_5flimits_2eproto

// ===================================================================

class MapLimits : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:cartographer.mapping_2d.proto.MapLimits) */ {
 public:
  MapLimits();
  virtual ~MapLimits();

  MapLimits(const MapLimits& from);

  inline MapLimits& operator=(const MapLimits& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MapLimits& default_instance();

  static inline const MapLimits* internal_default_instance() {
    return reinterpret_cast<const MapLimits*>(
               &_MapLimits_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(MapLimits* other);

  // implements Message ----------------------------------------------

  inline MapLimits* New() const PROTOBUF_FINAL { return New(NULL); }

  MapLimits* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const MapLimits& from);
  void MergeFrom(const MapLimits& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(MapLimits* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .cartographer.transform.proto.Vector2d max = 2;
  bool has_max() const;
  void clear_max();
  static const int kMaxFieldNumber = 2;
  const ::cartographer::transform::proto::Vector2d& max() const;
  ::cartographer::transform::proto::Vector2d* mutable_max();
  ::cartographer::transform::proto::Vector2d* release_max();
  void set_allocated_max(::cartographer::transform::proto::Vector2d* max);

  // optional .cartographer.mapping_2d.proto.CellLimits cell_limits = 3;
  bool has_cell_limits() const;
  void clear_cell_limits();
  static const int kCellLimitsFieldNumber = 3;
  const ::cartographer::mapping_2d::proto::CellLimits& cell_limits() const;
  ::cartographer::mapping_2d::proto::CellLimits* mutable_cell_limits();
  ::cartographer::mapping_2d::proto::CellLimits* release_cell_limits();
  void set_allocated_cell_limits(::cartographer::mapping_2d::proto::CellLimits* cell_limits);

  // optional double resolution = 1;
  bool has_resolution() const;
  void clear_resolution();
  static const int kResolutionFieldNumber = 1;
  double resolution() const;
  void set_resolution(double value);

  // @@protoc_insertion_point(class_scope:cartographer.mapping_2d.proto.MapLimits)
 private:
  void set_has_resolution();
  void clear_has_resolution();
  void set_has_max();
  void clear_has_max();
  void set_has_cell_limits();
  void clear_has_cell_limits();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::cartographer::transform::proto::Vector2d* max_;
  ::cartographer::mapping_2d::proto::CellLimits* cell_limits_;
  double resolution_;
  friend struct protobuf_cartographer_2fmapping_5f2d_2fproto_2fmap_5flimits_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// MapLimits

// optional double resolution = 1;
inline bool MapLimits::has_resolution() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void MapLimits::set_has_resolution() {
  _has_bits_[0] |= 0x00000004u;
}
inline void MapLimits::clear_has_resolution() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void MapLimits::clear_resolution() {
  resolution_ = 0;
  clear_has_resolution();
}
inline double MapLimits::resolution() const {
  // @@protoc_insertion_point(field_get:cartographer.mapping_2d.proto.MapLimits.resolution)
  return resolution_;
}
inline void MapLimits::set_resolution(double value) {
  set_has_resolution();
  resolution_ = value;
  // @@protoc_insertion_point(field_set:cartographer.mapping_2d.proto.MapLimits.resolution)
}

// optional .cartographer.transform.proto.Vector2d max = 2;
inline bool MapLimits::has_max() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MapLimits::set_has_max() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MapLimits::clear_has_max() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MapLimits::clear_max() {
  if (max_ != NULL) max_->::cartographer::transform::proto::Vector2d::Clear();
  clear_has_max();
}
inline const ::cartographer::transform::proto::Vector2d& MapLimits::max() const {
  // @@protoc_insertion_point(field_get:cartographer.mapping_2d.proto.MapLimits.max)
  return max_ != NULL ? *max_
                         : *::cartographer::transform::proto::Vector2d::internal_default_instance();
}
inline ::cartographer::transform::proto::Vector2d* MapLimits::mutable_max() {
  set_has_max();
  if (max_ == NULL) {
    max_ = new ::cartographer::transform::proto::Vector2d;
  }
  // @@protoc_insertion_point(field_mutable:cartographer.mapping_2d.proto.MapLimits.max)
  return max_;
}
inline ::cartographer::transform::proto::Vector2d* MapLimits::release_max() {
  // @@protoc_insertion_point(field_release:cartographer.mapping_2d.proto.MapLimits.max)
  clear_has_max();
  ::cartographer::transform::proto::Vector2d* temp = max_;
  max_ = NULL;
  return temp;
}
inline void MapLimits::set_allocated_max(::cartographer::transform::proto::Vector2d* max) {
  delete max_;
  max_ = max;
  if (max) {
    set_has_max();
  } else {
    clear_has_max();
  }
  // @@protoc_insertion_point(field_set_allocated:cartographer.mapping_2d.proto.MapLimits.max)
}

// optional .cartographer.mapping_2d.proto.CellLimits cell_limits = 3;
inline bool MapLimits::has_cell_limits() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void MapLimits::set_has_cell_limits() {
  _has_bits_[0] |= 0x00000002u;
}
inline void MapLimits::clear_has_cell_limits() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void MapLimits::clear_cell_limits() {
  if (cell_limits_ != NULL) cell_limits_->::cartographer::mapping_2d::proto::CellLimits::Clear();
  clear_has_cell_limits();
}
inline const ::cartographer::mapping_2d::proto::CellLimits& MapLimits::cell_limits() const {
  // @@protoc_insertion_point(field_get:cartographer.mapping_2d.proto.MapLimits.cell_limits)
  return cell_limits_ != NULL ? *cell_limits_
                         : *::cartographer::mapping_2d::proto::CellLimits::internal_default_instance();
}
inline ::cartographer::mapping_2d::proto::CellLimits* MapLimits::mutable_cell_limits() {
  set_has_cell_limits();
  if (cell_limits_ == NULL) {
    cell_limits_ = new ::cartographer::mapping_2d::proto::CellLimits;
  }
  // @@protoc_insertion_point(field_mutable:cartographer.mapping_2d.proto.MapLimits.cell_limits)
  return cell_limits_;
}
inline ::cartographer::mapping_2d::proto::CellLimits* MapLimits::release_cell_limits() {
  // @@protoc_insertion_point(field_release:cartographer.mapping_2d.proto.MapLimits.cell_limits)
  clear_has_cell_limits();
  ::cartographer::mapping_2d::proto::CellLimits* temp = cell_limits_;
  cell_limits_ = NULL;
  return temp;
}
inline void MapLimits::set_allocated_cell_limits(::cartographer::mapping_2d::proto::CellLimits* cell_limits) {
  delete cell_limits_;
  cell_limits_ = cell_limits;
  if (cell_limits) {
    set_has_cell_limits();
  } else {
    clear_has_cell_limits();
  }
  // @@protoc_insertion_point(field_set_allocated:cartographer.mapping_2d.proto.MapLimits.cell_limits)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)


}  // namespace proto
}  // namespace mapping_2d
}  // namespace cartographer

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_cartographer_2fmapping_5f2d_2fproto_2fmap_5flimits_2eproto__INCLUDED
