// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cartographer/mapping_2d/proto/range_data_inserter_options.proto

#ifndef PROTOBUF_cartographer_2fmapping_5f2d_2fproto_2frange_5fdata_5finserter_5foptions_2eproto__INCLUDED
#define PROTOBUF_cartographer_2fmapping_5f2d_2fproto_2frange_5fdata_5finserter_5foptions_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3003000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3003000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
namespace cartographer {
namespace mapping_2d {
namespace proto {
class RangeDataInserterOptions;
class RangeDataInserterOptionsDefaultTypeInternal;
extern RangeDataInserterOptionsDefaultTypeInternal _RangeDataInserterOptions_default_instance_;
}  // namespace proto
}  // namespace mapping_2d
}  // namespace cartographer

namespace cartographer {
namespace mapping_2d {
namespace proto {

namespace protobuf_cartographer_2fmapping_5f2d_2fproto_2frange_5fdata_5finserter_5foptions_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_cartographer_2fmapping_5f2d_2fproto_2frange_5fdata_5finserter_5foptions_2eproto

// ===================================================================

class RangeDataInserterOptions : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:cartographer.mapping_2d.proto.RangeDataInserterOptions) */ {
 public:
  RangeDataInserterOptions();
  virtual ~RangeDataInserterOptions();

  RangeDataInserterOptions(const RangeDataInserterOptions& from);

  inline RangeDataInserterOptions& operator=(const RangeDataInserterOptions& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const RangeDataInserterOptions& default_instance();

  static inline const RangeDataInserterOptions* internal_default_instance() {
    return reinterpret_cast<const RangeDataInserterOptions*>(
               &_RangeDataInserterOptions_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(RangeDataInserterOptions* other);

  // implements Message ----------------------------------------------

  inline RangeDataInserterOptions* New() const PROTOBUF_FINAL { return New(NULL); }

  RangeDataInserterOptions* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const RangeDataInserterOptions& from);
  void MergeFrom(const RangeDataInserterOptions& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(RangeDataInserterOptions* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional double hit_probability = 1;
  bool has_hit_probability() const;
  void clear_hit_probability();
  static const int kHitProbabilityFieldNumber = 1;
  double hit_probability() const;
  void set_hit_probability(double value);

  // optional double miss_probability = 2;
  bool has_miss_probability() const;
  void clear_miss_probability();
  static const int kMissProbabilityFieldNumber = 2;
  double miss_probability() const;
  void set_miss_probability(double value);

  // optional bool insert_free_space = 3;
  bool has_insert_free_space() const;
  void clear_insert_free_space();
  static const int kInsertFreeSpaceFieldNumber = 3;
  bool insert_free_space() const;
  void set_insert_free_space(bool value);

  // @@protoc_insertion_point(class_scope:cartographer.mapping_2d.proto.RangeDataInserterOptions)
 private:
  void set_has_hit_probability();
  void clear_has_hit_probability();
  void set_has_miss_probability();
  void clear_has_miss_probability();
  void set_has_insert_free_space();
  void clear_has_insert_free_space();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  double hit_probability_;
  double miss_probability_;
  bool insert_free_space_;
  friend struct protobuf_cartographer_2fmapping_5f2d_2fproto_2frange_5fdata_5finserter_5foptions_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// RangeDataInserterOptions

// optional double hit_probability = 1;
inline bool RangeDataInserterOptions::has_hit_probability() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void RangeDataInserterOptions::set_has_hit_probability() {
  _has_bits_[0] |= 0x00000001u;
}
inline void RangeDataInserterOptions::clear_has_hit_probability() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void RangeDataInserterOptions::clear_hit_probability() {
  hit_probability_ = 0;
  clear_has_hit_probability();
}
inline double RangeDataInserterOptions::hit_probability() const {
  // @@protoc_insertion_point(field_get:cartographer.mapping_2d.proto.RangeDataInserterOptions.hit_probability)
  return hit_probability_;
}
inline void RangeDataInserterOptions::set_hit_probability(double value) {
  set_has_hit_probability();
  hit_probability_ = value;
  // @@protoc_insertion_point(field_set:cartographer.mapping_2d.proto.RangeDataInserterOptions.hit_probability)
}

// optional double miss_probability = 2;
inline bool RangeDataInserterOptions::has_miss_probability() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void RangeDataInserterOptions::set_has_miss_probability() {
  _has_bits_[0] |= 0x00000002u;
}
inline void RangeDataInserterOptions::clear_has_miss_probability() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void RangeDataInserterOptions::clear_miss_probability() {
  miss_probability_ = 0;
  clear_has_miss_probability();
}
inline double RangeDataInserterOptions::miss_probability() const {
  // @@protoc_insertion_point(field_get:cartographer.mapping_2d.proto.RangeDataInserterOptions.miss_probability)
  return miss_probability_;
}
inline void RangeDataInserterOptions::set_miss_probability(double value) {
  set_has_miss_probability();
  miss_probability_ = value;
  // @@protoc_insertion_point(field_set:cartographer.mapping_2d.proto.RangeDataInserterOptions.miss_probability)
}

// optional bool insert_free_space = 3;
inline bool RangeDataInserterOptions::has_insert_free_space() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void RangeDataInserterOptions::set_has_insert_free_space() {
  _has_bits_[0] |= 0x00000004u;
}
inline void RangeDataInserterOptions::clear_has_insert_free_space() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void RangeDataInserterOptions::clear_insert_free_space() {
  insert_free_space_ = false;
  clear_has_insert_free_space();
}
inline bool RangeDataInserterOptions::insert_free_space() const {
  // @@protoc_insertion_point(field_get:cartographer.mapping_2d.proto.RangeDataInserterOptions.insert_free_space)
  return insert_free_space_;
}
inline void RangeDataInserterOptions::set_insert_free_space(bool value) {
  set_has_insert_free_space();
  insert_free_space_ = value;
  // @@protoc_insertion_point(field_set:cartographer.mapping_2d.proto.RangeDataInserterOptions.insert_free_space)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)


}  // namespace proto
}  // namespace mapping_2d
}  // namespace cartographer

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_cartographer_2fmapping_5f2d_2fproto_2frange_5fdata_5finserter_5foptions_2eproto__INCLUDED
