// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cartographer/sensor/proto/sensor.proto

#ifndef PROTOBUF_cartographer_2fsensor_2fproto_2fsensor_2eproto__INCLUDED
#define PROTOBUF_cartographer_2fsensor_2fproto_2fsensor_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3003000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3003000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "cartographer/transform/proto/transform.pb.h"
// @@protoc_insertion_point(includes)
namespace cartographer {
namespace sensor {
namespace proto {
class CompressedPointCloud;
class CompressedPointCloudDefaultTypeInternal;
extern CompressedPointCloudDefaultTypeInternal _CompressedPointCloud_default_instance_;
class CompressedRangeData;
class CompressedRangeDataDefaultTypeInternal;
extern CompressedRangeDataDefaultTypeInternal _CompressedRangeData_default_instance_;
class ImuData;
class ImuDataDefaultTypeInternal;
extern ImuDataDefaultTypeInternal _ImuData_default_instance_;
}  // namespace proto
}  // namespace sensor
}  // namespace cartographer

namespace cartographer {
namespace sensor {
namespace proto {

namespace protobuf_cartographer_2fsensor_2fproto_2fsensor_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_cartographer_2fsensor_2fproto_2fsensor_2eproto

// ===================================================================

class CompressedPointCloud : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:cartographer.sensor.proto.CompressedPointCloud) */ {
 public:
  CompressedPointCloud();
  virtual ~CompressedPointCloud();

  CompressedPointCloud(const CompressedPointCloud& from);

  inline CompressedPointCloud& operator=(const CompressedPointCloud& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CompressedPointCloud& default_instance();

  static inline const CompressedPointCloud* internal_default_instance() {
    return reinterpret_cast<const CompressedPointCloud*>(
               &_CompressedPointCloud_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(CompressedPointCloud* other);

  // implements Message ----------------------------------------------

  inline CompressedPointCloud* New() const PROTOBUF_FINAL { return New(NULL); }

  CompressedPointCloud* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const CompressedPointCloud& from);
  void MergeFrom(const CompressedPointCloud& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(CompressedPointCloud* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated int32 point_data = 3 [packed = true];
  int point_data_size() const;
  void clear_point_data();
  static const int kPointDataFieldNumber = 3;
  ::google::protobuf::int32 point_data(int index) const;
  void set_point_data(int index, ::google::protobuf::int32 value);
  void add_point_data(::google::protobuf::int32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      point_data() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_point_data();

  // optional int32 num_points = 1;
  bool has_num_points() const;
  void clear_num_points();
  static const int kNumPointsFieldNumber = 1;
  ::google::protobuf::int32 num_points() const;
  void set_num_points(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:cartographer.sensor.proto.CompressedPointCloud)
 private:
  void set_has_num_points();
  void clear_has_num_points();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > point_data_;
  mutable int _point_data_cached_byte_size_;
  ::google::protobuf::int32 num_points_;
  friend struct protobuf_cartographer_2fsensor_2fproto_2fsensor_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ImuData : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:cartographer.sensor.proto.ImuData) */ {
 public:
  ImuData();
  virtual ~ImuData();

  ImuData(const ImuData& from);

  inline ImuData& operator=(const ImuData& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ImuData& default_instance();

  static inline const ImuData* internal_default_instance() {
    return reinterpret_cast<const ImuData*>(
               &_ImuData_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(ImuData* other);

  // implements Message ----------------------------------------------

  inline ImuData* New() const PROTOBUF_FINAL { return New(NULL); }

  ImuData* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const ImuData& from);
  void MergeFrom(const ImuData& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ImuData* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .cartographer.transform.proto.Vector3d linear_acceleration = 2;
  bool has_linear_acceleration() const;
  void clear_linear_acceleration();
  static const int kLinearAccelerationFieldNumber = 2;
  const ::cartographer::transform::proto::Vector3d& linear_acceleration() const;
  ::cartographer::transform::proto::Vector3d* mutable_linear_acceleration();
  ::cartographer::transform::proto::Vector3d* release_linear_acceleration();
  void set_allocated_linear_acceleration(::cartographer::transform::proto::Vector3d* linear_acceleration);

  // optional .cartographer.transform.proto.Vector3d angular_velocity = 3;
  bool has_angular_velocity() const;
  void clear_angular_velocity();
  static const int kAngularVelocityFieldNumber = 3;
  const ::cartographer::transform::proto::Vector3d& angular_velocity() const;
  ::cartographer::transform::proto::Vector3d* mutable_angular_velocity();
  ::cartographer::transform::proto::Vector3d* release_angular_velocity();
  void set_allocated_angular_velocity(::cartographer::transform::proto::Vector3d* angular_velocity);

  // optional int64 timestamp = 1;
  bool has_timestamp() const;
  void clear_timestamp();
  static const int kTimestampFieldNumber = 1;
  ::google::protobuf::int64 timestamp() const;
  void set_timestamp(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:cartographer.sensor.proto.ImuData)
 private:
  void set_has_timestamp();
  void clear_has_timestamp();
  void set_has_linear_acceleration();
  void clear_has_linear_acceleration();
  void set_has_angular_velocity();
  void clear_has_angular_velocity();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::cartographer::transform::proto::Vector3d* linear_acceleration_;
  ::cartographer::transform::proto::Vector3d* angular_velocity_;
  ::google::protobuf::int64 timestamp_;
  friend struct protobuf_cartographer_2fsensor_2fproto_2fsensor_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class CompressedRangeData : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:cartographer.sensor.proto.CompressedRangeData) */ {
 public:
  CompressedRangeData();
  virtual ~CompressedRangeData();

  CompressedRangeData(const CompressedRangeData& from);

  inline CompressedRangeData& operator=(const CompressedRangeData& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CompressedRangeData& default_instance();

  static inline const CompressedRangeData* internal_default_instance() {
    return reinterpret_cast<const CompressedRangeData*>(
               &_CompressedRangeData_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    2;

  void Swap(CompressedRangeData* other);

  // implements Message ----------------------------------------------

  inline CompressedRangeData* New() const PROTOBUF_FINAL { return New(NULL); }

  CompressedRangeData* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const CompressedRangeData& from);
  void MergeFrom(const CompressedRangeData& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(CompressedRangeData* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .cartographer.transform.proto.Vector3f origin = 1;
  bool has_origin() const;
  void clear_origin();
  static const int kOriginFieldNumber = 1;
  const ::cartographer::transform::proto::Vector3f& origin() const;
  ::cartographer::transform::proto::Vector3f* mutable_origin();
  ::cartographer::transform::proto::Vector3f* release_origin();
  void set_allocated_origin(::cartographer::transform::proto::Vector3f* origin);

  // optional .cartographer.sensor.proto.CompressedPointCloud returns = 2;
  bool has_returns() const;
  void clear_returns();
  static const int kReturnsFieldNumber = 2;
  const ::cartographer::sensor::proto::CompressedPointCloud& returns() const;
  ::cartographer::sensor::proto::CompressedPointCloud* mutable_returns();
  ::cartographer::sensor::proto::CompressedPointCloud* release_returns();
  void set_allocated_returns(::cartographer::sensor::proto::CompressedPointCloud* returns);

  // optional .cartographer.sensor.proto.CompressedPointCloud misses = 3;
  bool has_misses() const;
  void clear_misses();
  static const int kMissesFieldNumber = 3;
  const ::cartographer::sensor::proto::CompressedPointCloud& misses() const;
  ::cartographer::sensor::proto::CompressedPointCloud* mutable_misses();
  ::cartographer::sensor::proto::CompressedPointCloud* release_misses();
  void set_allocated_misses(::cartographer::sensor::proto::CompressedPointCloud* misses);

  // @@protoc_insertion_point(class_scope:cartographer.sensor.proto.CompressedRangeData)
 private:
  void set_has_origin();
  void clear_has_origin();
  void set_has_returns();
  void clear_has_returns();
  void set_has_misses();
  void clear_has_misses();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::cartographer::transform::proto::Vector3f* origin_;
  ::cartographer::sensor::proto::CompressedPointCloud* returns_;
  ::cartographer::sensor::proto::CompressedPointCloud* misses_;
  friend struct protobuf_cartographer_2fsensor_2fproto_2fsensor_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// CompressedPointCloud

// optional int32 num_points = 1;
inline bool CompressedPointCloud::has_num_points() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CompressedPointCloud::set_has_num_points() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CompressedPointCloud::clear_has_num_points() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CompressedPointCloud::clear_num_points() {
  num_points_ = 0;
  clear_has_num_points();
}
inline ::google::protobuf::int32 CompressedPointCloud::num_points() const {
  // @@protoc_insertion_point(field_get:cartographer.sensor.proto.CompressedPointCloud.num_points)
  return num_points_;
}
inline void CompressedPointCloud::set_num_points(::google::protobuf::int32 value) {
  set_has_num_points();
  num_points_ = value;
  // @@protoc_insertion_point(field_set:cartographer.sensor.proto.CompressedPointCloud.num_points)
}

// repeated int32 point_data = 3 [packed = true];
inline int CompressedPointCloud::point_data_size() const {
  return point_data_.size();
}
inline void CompressedPointCloud::clear_point_data() {
  point_data_.Clear();
}
inline ::google::protobuf::int32 CompressedPointCloud::point_data(int index) const {
  // @@protoc_insertion_point(field_get:cartographer.sensor.proto.CompressedPointCloud.point_data)
  return point_data_.Get(index);
}
inline void CompressedPointCloud::set_point_data(int index, ::google::protobuf::int32 value) {
  point_data_.Set(index, value);
  // @@protoc_insertion_point(field_set:cartographer.sensor.proto.CompressedPointCloud.point_data)
}
inline void CompressedPointCloud::add_point_data(::google::protobuf::int32 value) {
  point_data_.Add(value);
  // @@protoc_insertion_point(field_add:cartographer.sensor.proto.CompressedPointCloud.point_data)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
CompressedPointCloud::point_data() const {
  // @@protoc_insertion_point(field_list:cartographer.sensor.proto.CompressedPointCloud.point_data)
  return point_data_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
CompressedPointCloud::mutable_point_data() {
  // @@protoc_insertion_point(field_mutable_list:cartographer.sensor.proto.CompressedPointCloud.point_data)
  return &point_data_;
}

// -------------------------------------------------------------------

// ImuData

// optional int64 timestamp = 1;
inline bool ImuData::has_timestamp() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void ImuData::set_has_timestamp() {
  _has_bits_[0] |= 0x00000004u;
}
inline void ImuData::clear_has_timestamp() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void ImuData::clear_timestamp() {
  timestamp_ = GOOGLE_LONGLONG(0);
  clear_has_timestamp();
}
inline ::google::protobuf::int64 ImuData::timestamp() const {
  // @@protoc_insertion_point(field_get:cartographer.sensor.proto.ImuData.timestamp)
  return timestamp_;
}
inline void ImuData::set_timestamp(::google::protobuf::int64 value) {
  set_has_timestamp();
  timestamp_ = value;
  // @@protoc_insertion_point(field_set:cartographer.sensor.proto.ImuData.timestamp)
}

// optional .cartographer.transform.proto.Vector3d linear_acceleration = 2;
inline bool ImuData::has_linear_acceleration() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ImuData::set_has_linear_acceleration() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ImuData::clear_has_linear_acceleration() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ImuData::clear_linear_acceleration() {
  if (linear_acceleration_ != NULL) linear_acceleration_->::cartographer::transform::proto::Vector3d::Clear();
  clear_has_linear_acceleration();
}
inline const ::cartographer::transform::proto::Vector3d& ImuData::linear_acceleration() const {
  // @@protoc_insertion_point(field_get:cartographer.sensor.proto.ImuData.linear_acceleration)
  return linear_acceleration_ != NULL ? *linear_acceleration_
                         : *::cartographer::transform::proto::Vector3d::internal_default_instance();
}
inline ::cartographer::transform::proto::Vector3d* ImuData::mutable_linear_acceleration() {
  set_has_linear_acceleration();
  if (linear_acceleration_ == NULL) {
    linear_acceleration_ = new ::cartographer::transform::proto::Vector3d;
  }
  // @@protoc_insertion_point(field_mutable:cartographer.sensor.proto.ImuData.linear_acceleration)
  return linear_acceleration_;
}
inline ::cartographer::transform::proto::Vector3d* ImuData::release_linear_acceleration() {
  // @@protoc_insertion_point(field_release:cartographer.sensor.proto.ImuData.linear_acceleration)
  clear_has_linear_acceleration();
  ::cartographer::transform::proto::Vector3d* temp = linear_acceleration_;
  linear_acceleration_ = NULL;
  return temp;
}
inline void ImuData::set_allocated_linear_acceleration(::cartographer::transform::proto::Vector3d* linear_acceleration) {
  delete linear_acceleration_;
  linear_acceleration_ = linear_acceleration;
  if (linear_acceleration) {
    set_has_linear_acceleration();
  } else {
    clear_has_linear_acceleration();
  }
  // @@protoc_insertion_point(field_set_allocated:cartographer.sensor.proto.ImuData.linear_acceleration)
}

// optional .cartographer.transform.proto.Vector3d angular_velocity = 3;
inline bool ImuData::has_angular_velocity() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ImuData::set_has_angular_velocity() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ImuData::clear_has_angular_velocity() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ImuData::clear_angular_velocity() {
  if (angular_velocity_ != NULL) angular_velocity_->::cartographer::transform::proto::Vector3d::Clear();
  clear_has_angular_velocity();
}
inline const ::cartographer::transform::proto::Vector3d& ImuData::angular_velocity() const {
  // @@protoc_insertion_point(field_get:cartographer.sensor.proto.ImuData.angular_velocity)
  return angular_velocity_ != NULL ? *angular_velocity_
                         : *::cartographer::transform::proto::Vector3d::internal_default_instance();
}
inline ::cartographer::transform::proto::Vector3d* ImuData::mutable_angular_velocity() {
  set_has_angular_velocity();
  if (angular_velocity_ == NULL) {
    angular_velocity_ = new ::cartographer::transform::proto::Vector3d;
  }
  // @@protoc_insertion_point(field_mutable:cartographer.sensor.proto.ImuData.angular_velocity)
  return angular_velocity_;
}
inline ::cartographer::transform::proto::Vector3d* ImuData::release_angular_velocity() {
  // @@protoc_insertion_point(field_release:cartographer.sensor.proto.ImuData.angular_velocity)
  clear_has_angular_velocity();
  ::cartographer::transform::proto::Vector3d* temp = angular_velocity_;
  angular_velocity_ = NULL;
  return temp;
}
inline void ImuData::set_allocated_angular_velocity(::cartographer::transform::proto::Vector3d* angular_velocity) {
  delete angular_velocity_;
  angular_velocity_ = angular_velocity;
  if (angular_velocity) {
    set_has_angular_velocity();
  } else {
    clear_has_angular_velocity();
  }
  // @@protoc_insertion_point(field_set_allocated:cartographer.sensor.proto.ImuData.angular_velocity)
}

// -------------------------------------------------------------------

// CompressedRangeData

// optional .cartographer.transform.proto.Vector3f origin = 1;
inline bool CompressedRangeData::has_origin() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CompressedRangeData::set_has_origin() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CompressedRangeData::clear_has_origin() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CompressedRangeData::clear_origin() {
  if (origin_ != NULL) origin_->::cartographer::transform::proto::Vector3f::Clear();
  clear_has_origin();
}
inline const ::cartographer::transform::proto::Vector3f& CompressedRangeData::origin() const {
  // @@protoc_insertion_point(field_get:cartographer.sensor.proto.CompressedRangeData.origin)
  return origin_ != NULL ? *origin_
                         : *::cartographer::transform::proto::Vector3f::internal_default_instance();
}
inline ::cartographer::transform::proto::Vector3f* CompressedRangeData::mutable_origin() {
  set_has_origin();
  if (origin_ == NULL) {
    origin_ = new ::cartographer::transform::proto::Vector3f;
  }
  // @@protoc_insertion_point(field_mutable:cartographer.sensor.proto.CompressedRangeData.origin)
  return origin_;
}
inline ::cartographer::transform::proto::Vector3f* CompressedRangeData::release_origin() {
  // @@protoc_insertion_point(field_release:cartographer.sensor.proto.CompressedRangeData.origin)
  clear_has_origin();
  ::cartographer::transform::proto::Vector3f* temp = origin_;
  origin_ = NULL;
  return temp;
}
inline void CompressedRangeData::set_allocated_origin(::cartographer::transform::proto::Vector3f* origin) {
  delete origin_;
  origin_ = origin;
  if (origin) {
    set_has_origin();
  } else {
    clear_has_origin();
  }
  // @@protoc_insertion_point(field_set_allocated:cartographer.sensor.proto.CompressedRangeData.origin)
}

// optional .cartographer.sensor.proto.CompressedPointCloud returns = 2;
inline bool CompressedRangeData::has_returns() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void CompressedRangeData::set_has_returns() {
  _has_bits_[0] |= 0x00000002u;
}
inline void CompressedRangeData::clear_has_returns() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void CompressedRangeData::clear_returns() {
  if (returns_ != NULL) returns_->::cartographer::sensor::proto::CompressedPointCloud::Clear();
  clear_has_returns();
}
inline const ::cartographer::sensor::proto::CompressedPointCloud& CompressedRangeData::returns() const {
  // @@protoc_insertion_point(field_get:cartographer.sensor.proto.CompressedRangeData.returns)
  return returns_ != NULL ? *returns_
                         : *::cartographer::sensor::proto::CompressedPointCloud::internal_default_instance();
}
inline ::cartographer::sensor::proto::CompressedPointCloud* CompressedRangeData::mutable_returns() {
  set_has_returns();
  if (returns_ == NULL) {
    returns_ = new ::cartographer::sensor::proto::CompressedPointCloud;
  }
  // @@protoc_insertion_point(field_mutable:cartographer.sensor.proto.CompressedRangeData.returns)
  return returns_;
}
inline ::cartographer::sensor::proto::CompressedPointCloud* CompressedRangeData::release_returns() {
  // @@protoc_insertion_point(field_release:cartographer.sensor.proto.CompressedRangeData.returns)
  clear_has_returns();
  ::cartographer::sensor::proto::CompressedPointCloud* temp = returns_;
  returns_ = NULL;
  return temp;
}
inline void CompressedRangeData::set_allocated_returns(::cartographer::sensor::proto::CompressedPointCloud* returns) {
  delete returns_;
  returns_ = returns;
  if (returns) {
    set_has_returns();
  } else {
    clear_has_returns();
  }
  // @@protoc_insertion_point(field_set_allocated:cartographer.sensor.proto.CompressedRangeData.returns)
}

// optional .cartographer.sensor.proto.CompressedPointCloud misses = 3;
inline bool CompressedRangeData::has_misses() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void CompressedRangeData::set_has_misses() {
  _has_bits_[0] |= 0x00000004u;
}
inline void CompressedRangeData::clear_has_misses() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void CompressedRangeData::clear_misses() {
  if (misses_ != NULL) misses_->::cartographer::sensor::proto::CompressedPointCloud::Clear();
  clear_has_misses();
}
inline const ::cartographer::sensor::proto::CompressedPointCloud& CompressedRangeData::misses() const {
  // @@protoc_insertion_point(field_get:cartographer.sensor.proto.CompressedRangeData.misses)
  return misses_ != NULL ? *misses_
                         : *::cartographer::sensor::proto::CompressedPointCloud::internal_default_instance();
}
inline ::cartographer::sensor::proto::CompressedPointCloud* CompressedRangeData::mutable_misses() {
  set_has_misses();
  if (misses_ == NULL) {
    misses_ = new ::cartographer::sensor::proto::CompressedPointCloud;
  }
  // @@protoc_insertion_point(field_mutable:cartographer.sensor.proto.CompressedRangeData.misses)
  return misses_;
}
inline ::cartographer::sensor::proto::CompressedPointCloud* CompressedRangeData::release_misses() {
  // @@protoc_insertion_point(field_release:cartographer.sensor.proto.CompressedRangeData.misses)
  clear_has_misses();
  ::cartographer::sensor::proto::CompressedPointCloud* temp = misses_;
  misses_ = NULL;
  return temp;
}
inline void CompressedRangeData::set_allocated_misses(::cartographer::sensor::proto::CompressedPointCloud* misses) {
  delete misses_;
  misses_ = misses;
  if (misses) {
    set_has_misses();
  } else {
    clear_has_misses();
  }
  // @@protoc_insertion_point(field_set_allocated:cartographer.sensor.proto.CompressedRangeData.misses)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


}  // namespace proto
}  // namespace sensor
}  // namespace cartographer

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_cartographer_2fsensor_2fproto_2fsensor_2eproto__INCLUDED
